/* tslint:disable */
/* eslint-disable */
/**
 * 全部  API 文档
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  JObjectApiResult,
  ServiceGroup,
  ServiceItem,
  ServiceProvider,
  Settings,
} from '../models/index';
import {
    JObjectApiResultFromJSON,
    JObjectApiResultToJSON,
    ServiceGroupFromJSON,
    ServiceGroupToJSON,
    ServiceItemFromJSON,
    ServiceItemToJSON,
    ServiceProviderFromJSON,
    ServiceProviderToJSON,
    SettingsFromJSON,
    SettingsToJSON,
} from '../models/index';

export interface ServiceSettingRequest {
    id: number;
}

export interface ServiceSettingDeleteRequest {
    id: number;
}

export interface ServiceSettingGroupRequest {
    id: number;
}

export interface ServiceSettingGroupDeleteRequest {
    id: number;
}

export interface ServiceSettingGroupPostRequest {
    serviceGroup?: ServiceGroup;
}

export interface ServiceSettingGroupPutRequest {
    id: number;
    serviceGroup?: ServiceGroup;
}

export interface ServiceSettingGroupsRequest {
    providerId?: number;
    showFlag?: boolean;
}

export interface ServiceSettingItemRequest {
    id: number;
}

export interface ServiceSettingItemDeleteRequest {
    id: number;
}

export interface ServiceSettingItemPostRequest {
    serviceItem?: ServiceItem;
}

export interface ServiceSettingItemPutRequest {
    id: number;
    serviceItem?: ServiceItem;
}

export interface ServiceSettingItemsRequest {
    bizCode?: string;
    providerCode?: string;
    groupCode?: string;
    showFlag?: boolean;
}

export interface ServiceSettingPostRequest {
    settings?: Settings;
}

export interface ServiceSettingProviderRequest {
    id: number;
}

export interface ServiceSettingProviderDeleteRequest {
    id: number;
}

export interface ServiceSettingProviderPostRequest {
    serviceProvider?: ServiceProvider;
}

export interface ServiceSettingProviderPutRequest {
    id: number;
    serviceProvider?: ServiceProvider;
}

export interface ServiceSettingProvidersRequest {
    bizCode?: string;
    showFlag?: boolean;
}

export interface ServiceSettingPutRequest {
    id: number;
    settings?: Settings;
}

export interface ServiceSettingsRequest {
    bizCode: string;
    bizId: string;
    providerCode?: string;
    groupCode?: string;
    tag?: string;
    code?: string;
}

/**
 * ServiceSettingApi - interface
 * 
 * @export
 * @interface ServiceSettingApiInterface
 */
export interface ServiceSettingApiInterface {
    /**
     * 
     * @summary 配置详情
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ServiceSettingApiInterface
     */
    serviceSettingRaw(requestParameters: ServiceSettingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JObjectApiResult>>;

    /**
     * 配置详情
     */
    serviceSetting(requestParameters: ServiceSettingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JObjectApiResult>;

    /**
     * 
     * @summary 删除配置
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ServiceSettingApiInterface
     */
    serviceSettingDeleteRaw(requestParameters: ServiceSettingDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JObjectApiResult>>;

    /**
     * 删除配置
     */
    serviceSettingDelete(requestParameters: ServiceSettingDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JObjectApiResult>;

    /**
     * 
     * @summary 服务分组详情
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ServiceSettingApiInterface
     */
    serviceSettingGroupRaw(requestParameters: ServiceSettingGroupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JObjectApiResult>>;

    /**
     * 服务分组详情
     */
    serviceSettingGroup(requestParameters: ServiceSettingGroupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JObjectApiResult>;

    /**
     * 
     * @summary 删除服务分组
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ServiceSettingApiInterface
     */
    serviceSettingGroupDeleteRaw(requestParameters: ServiceSettingGroupDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JObjectApiResult>>;

    /**
     * 删除服务分组
     */
    serviceSettingGroupDelete(requestParameters: ServiceSettingGroupDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JObjectApiResult>;

    /**
     * 
     * @summary 添加服务分组
     * @param {ServiceGroup} [serviceGroup] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ServiceSettingApiInterface
     */
    serviceSettingGroupPostRaw(requestParameters: ServiceSettingGroupPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JObjectApiResult>>;

    /**
     * 添加服务分组
     */
    serviceSettingGroupPost(requestParameters: ServiceSettingGroupPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JObjectApiResult>;

    /**
     * 
     * @summary 更新服务分组
     * @param {number} id 
     * @param {ServiceGroup} [serviceGroup] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ServiceSettingApiInterface
     */
    serviceSettingGroupPutRaw(requestParameters: ServiceSettingGroupPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JObjectApiResult>>;

    /**
     * 更新服务分组
     */
    serviceSettingGroupPut(requestParameters: ServiceSettingGroupPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JObjectApiResult>;

    /**
     * 
     * @summary 服务分组
     * @param {number} [providerId] 
     * @param {boolean} [showFlag] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ServiceSettingApiInterface
     */
    serviceSettingGroupsRaw(requestParameters: ServiceSettingGroupsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JObjectApiResult>>;

    /**
     * 服务分组
     */
    serviceSettingGroups(requestParameters: ServiceSettingGroupsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JObjectApiResult>;

    /**
     * 
     * @summary 服务配置详情
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ServiceSettingApiInterface
     */
    serviceSettingItemRaw(requestParameters: ServiceSettingItemRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JObjectApiResult>>;

    /**
     * 服务配置详情
     */
    serviceSettingItem(requestParameters: ServiceSettingItemRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JObjectApiResult>;

    /**
     * 
     * @summary 删除服务配置
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ServiceSettingApiInterface
     */
    serviceSettingItemDeleteRaw(requestParameters: ServiceSettingItemDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JObjectApiResult>>;

    /**
     * 删除服务配置
     */
    serviceSettingItemDelete(requestParameters: ServiceSettingItemDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JObjectApiResult>;

    /**
     * 
     * @summary 添加服务配置
     * @param {ServiceItem} [serviceItem] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ServiceSettingApiInterface
     */
    serviceSettingItemPostRaw(requestParameters: ServiceSettingItemPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JObjectApiResult>>;

    /**
     * 添加服务配置
     */
    serviceSettingItemPost(requestParameters: ServiceSettingItemPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JObjectApiResult>;

    /**
     * 
     * @summary 更新服务配置
     * @param {number} id 
     * @param {ServiceItem} [serviceItem] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ServiceSettingApiInterface
     */
    serviceSettingItemPutRaw(requestParameters: ServiceSettingItemPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JObjectApiResult>>;

    /**
     * 更新服务配置
     */
    serviceSettingItemPut(requestParameters: ServiceSettingItemPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JObjectApiResult>;

    /**
     * 
     * @summary 服务配置列表
     * @param {string} [bizCode] 
     * @param {string} [providerCode] 
     * @param {string} [groupCode] 
     * @param {boolean} [showFlag] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ServiceSettingApiInterface
     */
    serviceSettingItemsRaw(requestParameters: ServiceSettingItemsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JObjectApiResult>>;

    /**
     * 服务配置列表
     */
    serviceSettingItems(requestParameters: ServiceSettingItemsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JObjectApiResult>;

    /**
     * 
     * @summary 增加配置
     * @param {Settings} [settings] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ServiceSettingApiInterface
     */
    serviceSettingPostRaw(requestParameters: ServiceSettingPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JObjectApiResult>>;

    /**
     * 增加配置
     */
    serviceSettingPost(requestParameters: ServiceSettingPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JObjectApiResult>;

    /**
     * 
     * @summary 服务商详情
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ServiceSettingApiInterface
     */
    serviceSettingProviderRaw(requestParameters: ServiceSettingProviderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JObjectApiResult>>;

    /**
     * 服务商详情
     */
    serviceSettingProvider(requestParameters: ServiceSettingProviderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JObjectApiResult>;

    /**
     * 
     * @summary 删除服务商
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ServiceSettingApiInterface
     */
    serviceSettingProviderDeleteRaw(requestParameters: ServiceSettingProviderDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JObjectApiResult>>;

    /**
     * 删除服务商
     */
    serviceSettingProviderDelete(requestParameters: ServiceSettingProviderDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JObjectApiResult>;

    /**
     * 
     * @summary 添加服务商
     * @param {ServiceProvider} [serviceProvider] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ServiceSettingApiInterface
     */
    serviceSettingProviderPostRaw(requestParameters: ServiceSettingProviderPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JObjectApiResult>>;

    /**
     * 添加服务商
     */
    serviceSettingProviderPost(requestParameters: ServiceSettingProviderPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JObjectApiResult>;

    /**
     * 
     * @summary 更新服务商
     * @param {number} id 
     * @param {ServiceProvider} [serviceProvider] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ServiceSettingApiInterface
     */
    serviceSettingProviderPutRaw(requestParameters: ServiceSettingProviderPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JObjectApiResult>>;

    /**
     * 更新服务商
     */
    serviceSettingProviderPut(requestParameters: ServiceSettingProviderPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JObjectApiResult>;

    /**
     * 
     * @summary 服务商列表
     * @param {string} [bizCode] 
     * @param {boolean} [showFlag] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ServiceSettingApiInterface
     */
    serviceSettingProvidersRaw(requestParameters: ServiceSettingProvidersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JObjectApiResult>>;

    /**
     * 服务商列表
     */
    serviceSettingProviders(requestParameters: ServiceSettingProvidersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JObjectApiResult>;

    /**
     * 
     * @summary 更新配置
     * @param {number} id 
     * @param {Settings} [settings] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ServiceSettingApiInterface
     */
    serviceSettingPutRaw(requestParameters: ServiceSettingPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JObjectApiResult>>;

    /**
     * 更新配置
     */
    serviceSettingPut(requestParameters: ServiceSettingPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JObjectApiResult>;

    /**
     * 
     * @summary 配置列表
     * @param {string} bizCode 
     * @param {string} bizId 
     * @param {string} [providerCode] 
     * @param {string} [groupCode] 
     * @param {string} [tag] 
     * @param {string} [code] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ServiceSettingApiInterface
     */
    serviceSettingsRaw(requestParameters: ServiceSettingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JObjectApiResult>>;

    /**
     * 配置列表
     */
    serviceSettings(requestParameters: ServiceSettingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JObjectApiResult>;

}

/**
 * 
 */
export class ServiceSettingApi extends runtime.BaseAPI implements ServiceSettingApiInterface {

    /**
     * 配置详情
     */
    async serviceSettingRaw(requestParameters: ServiceSettingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JObjectApiResult>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling serviceSetting().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/ServiceSetting/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => JObjectApiResultFromJSON(jsonValue));
    }

    /**
     * 配置详情
     */
    async serviceSetting(requestParameters: ServiceSettingRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JObjectApiResult> {
        const response = await this.serviceSettingRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 删除配置
     */
    async serviceSettingDeleteRaw(requestParameters: ServiceSettingDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JObjectApiResult>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling serviceSettingDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/ServiceSetting/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => JObjectApiResultFromJSON(jsonValue));
    }

    /**
     * 删除配置
     */
    async serviceSettingDelete(requestParameters: ServiceSettingDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JObjectApiResult> {
        const response = await this.serviceSettingDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 服务分组详情
     */
    async serviceSettingGroupRaw(requestParameters: ServiceSettingGroupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JObjectApiResult>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling serviceSettingGroup().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/ServiceSetting/Groups/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => JObjectApiResultFromJSON(jsonValue));
    }

    /**
     * 服务分组详情
     */
    async serviceSettingGroup(requestParameters: ServiceSettingGroupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JObjectApiResult> {
        const response = await this.serviceSettingGroupRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 删除服务分组
     */
    async serviceSettingGroupDeleteRaw(requestParameters: ServiceSettingGroupDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JObjectApiResult>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling serviceSettingGroupDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/ServiceSetting/Groups/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => JObjectApiResultFromJSON(jsonValue));
    }

    /**
     * 删除服务分组
     */
    async serviceSettingGroupDelete(requestParameters: ServiceSettingGroupDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JObjectApiResult> {
        const response = await this.serviceSettingGroupDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 添加服务分组
     */
    async serviceSettingGroupPostRaw(requestParameters: ServiceSettingGroupPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JObjectApiResult>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json-patch+json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/ServiceSetting/Groups`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ServiceGroupToJSON(requestParameters['serviceGroup']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => JObjectApiResultFromJSON(jsonValue));
    }

    /**
     * 添加服务分组
     */
    async serviceSettingGroupPost(requestParameters: ServiceSettingGroupPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JObjectApiResult> {
        const response = await this.serviceSettingGroupPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 更新服务分组
     */
    async serviceSettingGroupPutRaw(requestParameters: ServiceSettingGroupPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JObjectApiResult>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling serviceSettingGroupPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json-patch+json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/ServiceSetting/Groups/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: ServiceGroupToJSON(requestParameters['serviceGroup']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => JObjectApiResultFromJSON(jsonValue));
    }

    /**
     * 更新服务分组
     */
    async serviceSettingGroupPut(requestParameters: ServiceSettingGroupPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JObjectApiResult> {
        const response = await this.serviceSettingGroupPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 服务分组
     */
    async serviceSettingGroupsRaw(requestParameters: ServiceSettingGroupsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JObjectApiResult>> {
        const queryParameters: any = {};

        if (requestParameters['providerId'] != null) {
            queryParameters['providerId'] = requestParameters['providerId'];
        }

        if (requestParameters['showFlag'] != null) {
            queryParameters['showFlag'] = requestParameters['showFlag'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/ServiceSetting/Groups`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => JObjectApiResultFromJSON(jsonValue));
    }

    /**
     * 服务分组
     */
    async serviceSettingGroups(requestParameters: ServiceSettingGroupsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JObjectApiResult> {
        const response = await this.serviceSettingGroupsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 服务配置详情
     */
    async serviceSettingItemRaw(requestParameters: ServiceSettingItemRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JObjectApiResult>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling serviceSettingItem().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/ServiceSetting/Items/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => JObjectApiResultFromJSON(jsonValue));
    }

    /**
     * 服务配置详情
     */
    async serviceSettingItem(requestParameters: ServiceSettingItemRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JObjectApiResult> {
        const response = await this.serviceSettingItemRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 删除服务配置
     */
    async serviceSettingItemDeleteRaw(requestParameters: ServiceSettingItemDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JObjectApiResult>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling serviceSettingItemDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/ServiceSetting/Items/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => JObjectApiResultFromJSON(jsonValue));
    }

    /**
     * 删除服务配置
     */
    async serviceSettingItemDelete(requestParameters: ServiceSettingItemDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JObjectApiResult> {
        const response = await this.serviceSettingItemDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 添加服务配置
     */
    async serviceSettingItemPostRaw(requestParameters: ServiceSettingItemPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JObjectApiResult>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json-patch+json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/ServiceSetting/Items`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ServiceItemToJSON(requestParameters['serviceItem']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => JObjectApiResultFromJSON(jsonValue));
    }

    /**
     * 添加服务配置
     */
    async serviceSettingItemPost(requestParameters: ServiceSettingItemPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JObjectApiResult> {
        const response = await this.serviceSettingItemPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 更新服务配置
     */
    async serviceSettingItemPutRaw(requestParameters: ServiceSettingItemPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JObjectApiResult>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling serviceSettingItemPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json-patch+json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/ServiceSetting/Items/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: ServiceItemToJSON(requestParameters['serviceItem']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => JObjectApiResultFromJSON(jsonValue));
    }

    /**
     * 更新服务配置
     */
    async serviceSettingItemPut(requestParameters: ServiceSettingItemPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JObjectApiResult> {
        const response = await this.serviceSettingItemPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 服务配置列表
     */
    async serviceSettingItemsRaw(requestParameters: ServiceSettingItemsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JObjectApiResult>> {
        const queryParameters: any = {};

        if (requestParameters['bizCode'] != null) {
            queryParameters['bizCode'] = requestParameters['bizCode'];
        }

        if (requestParameters['providerCode'] != null) {
            queryParameters['providerCode'] = requestParameters['providerCode'];
        }

        if (requestParameters['groupCode'] != null) {
            queryParameters['groupCode'] = requestParameters['groupCode'];
        }

        if (requestParameters['showFlag'] != null) {
            queryParameters['showFlag'] = requestParameters['showFlag'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/ServiceSetting/Items`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => JObjectApiResultFromJSON(jsonValue));
    }

    /**
     * 服务配置列表
     */
    async serviceSettingItems(requestParameters: ServiceSettingItemsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JObjectApiResult> {
        const response = await this.serviceSettingItemsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 增加配置
     */
    async serviceSettingPostRaw(requestParameters: ServiceSettingPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JObjectApiResult>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json-patch+json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/ServiceSetting`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SettingsToJSON(requestParameters['settings']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => JObjectApiResultFromJSON(jsonValue));
    }

    /**
     * 增加配置
     */
    async serviceSettingPost(requestParameters: ServiceSettingPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JObjectApiResult> {
        const response = await this.serviceSettingPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 服务商详情
     */
    async serviceSettingProviderRaw(requestParameters: ServiceSettingProviderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JObjectApiResult>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling serviceSettingProvider().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/ServiceSetting/Providers/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => JObjectApiResultFromJSON(jsonValue));
    }

    /**
     * 服务商详情
     */
    async serviceSettingProvider(requestParameters: ServiceSettingProviderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JObjectApiResult> {
        const response = await this.serviceSettingProviderRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 删除服务商
     */
    async serviceSettingProviderDeleteRaw(requestParameters: ServiceSettingProviderDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JObjectApiResult>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling serviceSettingProviderDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/ServiceSetting/Providers/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => JObjectApiResultFromJSON(jsonValue));
    }

    /**
     * 删除服务商
     */
    async serviceSettingProviderDelete(requestParameters: ServiceSettingProviderDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JObjectApiResult> {
        const response = await this.serviceSettingProviderDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 添加服务商
     */
    async serviceSettingProviderPostRaw(requestParameters: ServiceSettingProviderPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JObjectApiResult>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json-patch+json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/ServiceSetting/Providers`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ServiceProviderToJSON(requestParameters['serviceProvider']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => JObjectApiResultFromJSON(jsonValue));
    }

    /**
     * 添加服务商
     */
    async serviceSettingProviderPost(requestParameters: ServiceSettingProviderPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JObjectApiResult> {
        const response = await this.serviceSettingProviderPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 更新服务商
     */
    async serviceSettingProviderPutRaw(requestParameters: ServiceSettingProviderPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JObjectApiResult>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling serviceSettingProviderPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json-patch+json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/ServiceSetting/Providers/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: ServiceProviderToJSON(requestParameters['serviceProvider']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => JObjectApiResultFromJSON(jsonValue));
    }

    /**
     * 更新服务商
     */
    async serviceSettingProviderPut(requestParameters: ServiceSettingProviderPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JObjectApiResult> {
        const response = await this.serviceSettingProviderPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 服务商列表
     */
    async serviceSettingProvidersRaw(requestParameters: ServiceSettingProvidersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JObjectApiResult>> {
        const queryParameters: any = {};

        if (requestParameters['bizCode'] != null) {
            queryParameters['bizCode'] = requestParameters['bizCode'];
        }

        if (requestParameters['showFlag'] != null) {
            queryParameters['showFlag'] = requestParameters['showFlag'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/ServiceSetting/Providers`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => JObjectApiResultFromJSON(jsonValue));
    }

    /**
     * 服务商列表
     */
    async serviceSettingProviders(requestParameters: ServiceSettingProvidersRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JObjectApiResult> {
        const response = await this.serviceSettingProvidersRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 更新配置
     */
    async serviceSettingPutRaw(requestParameters: ServiceSettingPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JObjectApiResult>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling serviceSettingPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json-patch+json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/ServiceSetting/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: SettingsToJSON(requestParameters['settings']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => JObjectApiResultFromJSON(jsonValue));
    }

    /**
     * 更新配置
     */
    async serviceSettingPut(requestParameters: ServiceSettingPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JObjectApiResult> {
        const response = await this.serviceSettingPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 配置列表
     */
    async serviceSettingsRaw(requestParameters: ServiceSettingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JObjectApiResult>> {
        if (requestParameters['bizCode'] == null) {
            throw new runtime.RequiredError(
                'bizCode',
                'Required parameter "bizCode" was null or undefined when calling serviceSettings().'
            );
        }

        if (requestParameters['bizId'] == null) {
            throw new runtime.RequiredError(
                'bizId',
                'Required parameter "bizId" was null or undefined when calling serviceSettings().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['bizCode'] != null) {
            queryParameters['bizCode'] = requestParameters['bizCode'];
        }

        if (requestParameters['bizId'] != null) {
            queryParameters['bizId'] = requestParameters['bizId'];
        }

        if (requestParameters['providerCode'] != null) {
            queryParameters['providerCode'] = requestParameters['providerCode'];
        }

        if (requestParameters['groupCode'] != null) {
            queryParameters['groupCode'] = requestParameters['groupCode'];
        }

        if (requestParameters['tag'] != null) {
            queryParameters['tag'] = requestParameters['tag'];
        }

        if (requestParameters['code'] != null) {
            queryParameters['code'] = requestParameters['code'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/ServiceSetting`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => JObjectApiResultFromJSON(jsonValue));
    }

    /**
     * 配置列表
     */
    async serviceSettings(requestParameters: ServiceSettingsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JObjectApiResult> {
        const response = await this.serviceSettingsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
