/* tslint:disable */
/* eslint-disable */
/**
 * 全部  API 文档
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AccessTokenPutRequest
 */
export interface AccessTokenPutRequest {
    /**
     * 
     * @type {string}
     * @memberof AccessTokenPutRequest
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof AccessTokenPutRequest
     */
    tags?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AccessTokenPutRequest
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AccessTokenPutRequest
     */
    permissions?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof AccessTokenPutRequest
     */
    enable?: boolean;
}

/**
 * Check if a given object implements the AccessTokenPutRequest interface.
 */
export function instanceOfAccessTokenPutRequest(value: object): value is AccessTokenPutRequest {
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function AccessTokenPutRequestFromJSON(json: any): AccessTokenPutRequest {
    return AccessTokenPutRequestFromJSONTyped(json, false);
}

export function AccessTokenPutRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccessTokenPutRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'tags': json['tags'] == null ? undefined : json['tags'],
        'description': json['description'] == null ? undefined : json['description'],
        'permissions': json['permissions'] == null ? undefined : json['permissions'],
        'enable': json['enable'] == null ? undefined : json['enable'],
    };
}

export function AccessTokenPutRequestToJSON(json: any): AccessTokenPutRequest {
    return AccessTokenPutRequestToJSONTyped(json, false);
}

export function AccessTokenPutRequestToJSONTyped(value?: AccessTokenPutRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'tags': value['tags'],
        'description': value['description'],
        'permissions': value['permissions'],
        'enable': value['enable'],
    };
}

