/* tslint:disable */
/* eslint-disable */
/**
 * 用户全部 API 文档
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AlipayTradeQueryResponse } from './AlipayTradeQueryResponse';
import {
    AlipayTradeQueryResponseFromJSON,
    AlipayTradeQueryResponseFromJSONTyped,
    AlipayTradeQueryResponseToJSON,
    AlipayTradeQueryResponseToJSONTyped,
} from './AlipayTradeQueryResponse';

/**
 * 
 * @export
 * @interface AlipayTradeQueryResponseApiResponse
 */
export interface AlipayTradeQueryResponseApiResponse {
    /**
     * 状态码
     * @type {number}
     * @memberof AlipayTradeQueryResponseApiResponse
     */
    code?: number;
    /**
     * 
     * @type {AlipayTradeQueryResponse}
     * @memberof AlipayTradeQueryResponseApiResponse
     */
    data?: AlipayTradeQueryResponse;
    /**
     * 错误信息
     * @type {string}
     * @memberof AlipayTradeQueryResponseApiResponse
     */
    error?: string | null;
}

/**
 * Check if a given object implements the AlipayTradeQueryResponseApiResponse interface.
 */
export function instanceOfAlipayTradeQueryResponseApiResponse(value: object): value is AlipayTradeQueryResponseApiResponse {
    return true;
}

export function AlipayTradeQueryResponseApiResponseFromJSON(json: any): AlipayTradeQueryResponseApiResponse {
    return AlipayTradeQueryResponseApiResponseFromJSONTyped(json, false);
}

export function AlipayTradeQueryResponseApiResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AlipayTradeQueryResponseApiResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'data': json['data'] == null ? undefined : AlipayTradeQueryResponseFromJSON(json['data']),
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function AlipayTradeQueryResponseApiResponseToJSON(json: any): AlipayTradeQueryResponseApiResponse {
    return AlipayTradeQueryResponseApiResponseToJSONTyped(json, false);
}

export function AlipayTradeQueryResponseApiResponseToJSONTyped(value?: AlipayTradeQueryResponseApiResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'data': AlipayTradeQueryResponseToJSON(value['data']),
        'error': value['error'],
    };
}

