/* tslint:disable */
/* eslint-disable */
/**
 * 用户全部 API 文档
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FulfillmentDetail } from './FulfillmentDetail';
import {
    FulfillmentDetailFromJSON,
    FulfillmentDetailFromJSONTyped,
    FulfillmentDetailToJSON,
    FulfillmentDetailToJSONTyped,
} from './FulfillmentDetail';
import type { ChargeInfo } from './ChargeInfo';
import {
    ChargeInfoFromJSON,
    ChargeInfoFromJSONTyped,
    ChargeInfoToJSON,
    ChargeInfoToJSONTyped,
} from './ChargeInfo';
import type { EnterprisePayInfo } from './EnterprisePayInfo';
import {
    EnterprisePayInfoFromJSON,
    EnterprisePayInfoFromJSONTyped,
    EnterprisePayInfoToJSON,
    EnterprisePayInfoToJSONTyped,
} from './EnterprisePayInfo';
import type { TradeFundBill } from './TradeFundBill';
import {
    TradeFundBillFromJSON,
    TradeFundBillFromJSONTyped,
    TradeFundBillToJSON,
    TradeFundBillToJSONTyped,
} from './TradeFundBill';
import type { TradeSettleInfo } from './TradeSettleInfo';
import {
    TradeSettleInfoFromJSON,
    TradeSettleInfoFromJSONTyped,
    TradeSettleInfoToJSON,
    TradeSettleInfoToJSONTyped,
} from './TradeSettleInfo';
import type { BkAgentRespInfo } from './BkAgentRespInfo';
import {
    BkAgentRespInfoFromJSON,
    BkAgentRespInfoFromJSONTyped,
    BkAgentRespInfoToJSON,
    BkAgentRespInfoToJSONTyped,
} from './BkAgentRespInfo';
import type { GoodsDetail } from './GoodsDetail';
import {
    GoodsDetailFromJSON,
    GoodsDetailFromJSONTyped,
    GoodsDetailToJSON,
    GoodsDetailToJSONTyped,
} from './GoodsDetail';
import type { IntactChargeInfo } from './IntactChargeInfo';
import {
    IntactChargeInfoFromJSON,
    IntactChargeInfoFromJSONTyped,
    IntactChargeInfoToJSON,
    IntactChargeInfoToJSONTyped,
} from './IntactChargeInfo';
import type { PaymentInfoWithId } from './PaymentInfoWithId';
import {
    PaymentInfoWithIdFromJSON,
    PaymentInfoWithIdFromJSONTyped,
    PaymentInfoWithIdToJSON,
    PaymentInfoWithIdToJSONTyped,
} from './PaymentInfoWithId';
import type { TapPayInfo } from './TapPayInfo';
import {
    TapPayInfoFromJSON,
    TapPayInfoFromJSONTyped,
    TapPayInfoToJSON,
    TapPayInfoToJSONTyped,
} from './TapPayInfo';
import type { HbFqPayInfo } from './HbFqPayInfo';
import {
    HbFqPayInfoFromJSON,
    HbFqPayInfoFromJSONTyped,
    HbFqPayInfoToJSON,
    HbFqPayInfoToJSONTyped,
} from './HbFqPayInfo';
import type { VoucherDetail } from './VoucherDetail';
import {
    VoucherDetailFromJSON,
    VoucherDetailFromJSONTyped,
    VoucherDetailToJSON,
    VoucherDetailToJSONTyped,
} from './VoucherDetail';

/**
 * 
 * @export
 * @interface AlipayTradeQueryResponse
 */
export interface AlipayTradeQueryResponse {
    /**
     * 
     * @type {string}
     * @memberof AlipayTradeQueryResponse
     */
    code?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AlipayTradeQueryResponse
     */
    msg?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AlipayTradeQueryResponse
     */
    subCode?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AlipayTradeQueryResponse
     */
    subMsg?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof AlipayTradeQueryResponse
     */
    readonly isError?: boolean;
    /**
     * 
     * @type {string}
     * @memberof AlipayTradeQueryResponse
     */
    additionalStatus?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AlipayTradeQueryResponse
     */
    alipayStoreId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AlipayTradeQueryResponse
     */
    alipaySubMerchantId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AlipayTradeQueryResponse
     */
    asyncPayApplyStatus?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AlipayTradeQueryResponse
     */
    authTradePayMode?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AlipayTradeQueryResponse
     */
    bizSettleMode?: string | null;
    /**
     * 
     * @type {BkAgentRespInfo}
     * @memberof AlipayTradeQueryResponse
     */
    bkagentRespInfo?: BkAgentRespInfo;
    /**
     * 
     * @type {string}
     * @memberof AlipayTradeQueryResponse
     */
    body?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AlipayTradeQueryResponse
     */
    buyerLogonId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AlipayTradeQueryResponse
     */
    buyerOpenId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AlipayTradeQueryResponse
     */
    buyerPayAmount?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AlipayTradeQueryResponse
     */
    buyerUserId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AlipayTradeQueryResponse
     */
    buyerUserName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AlipayTradeQueryResponse
     */
    buyerUserType?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AlipayTradeQueryResponse
     */
    cashierType?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AlipayTradeQueryResponse
     */
    chargeAmount?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AlipayTradeQueryResponse
     */
    chargeFlags?: string | null;
    /**
     * 
     * @type {Array<ChargeInfo>}
     * @memberof AlipayTradeQueryResponse
     */
    chargeInfoList?: Array<ChargeInfo> | null;
    /**
     * 
     * @type {string}
     * @memberof AlipayTradeQueryResponse
     */
    creditBizOrderId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AlipayTradeQueryResponse
     */
    creditPayMode?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AlipayTradeQueryResponse
     */
    discountAmount?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AlipayTradeQueryResponse
     */
    discountGoodsDetail?: string | null;
    /**
     * 
     * @type {EnterprisePayInfo}
     * @memberof AlipayTradeQueryResponse
     */
    enterprisePayInfo?: EnterprisePayInfo;
    /**
     * 
     * @type {string}
     * @memberof AlipayTradeQueryResponse
     */
    extInfos?: string | null;
    /**
     * 
     * @type {Array<FulfillmentDetail>}
     * @memberof AlipayTradeQueryResponse
     */
    fulfillmentDetailList?: Array<FulfillmentDetail> | null;
    /**
     * 
     * @type {Array<TradeFundBill>}
     * @memberof AlipayTradeQueryResponse
     */
    fundBillList?: Array<TradeFundBill> | null;
    /**
     * 
     * @type {HbFqPayInfo}
     * @memberof AlipayTradeQueryResponse
     */
    hbFqPayInfo?: HbFqPayInfo;
    /**
     * 
     * @type {string}
     * @memberof AlipayTradeQueryResponse
     */
    hybAmount?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AlipayTradeQueryResponse
     */
    industrySepcDetail?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AlipayTradeQueryResponse
     */
    industrySepcDetailAcc?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AlipayTradeQueryResponse
     */
    industrySepcDetailGov?: string | null;
    /**
     * 
     * @type {Array<IntactChargeInfo>}
     * @memberof AlipayTradeQueryResponse
     */
    intactChargeInfoList?: Array<IntactChargeInfo> | null;
    /**
     * 
     * @type {string}
     * @memberof AlipayTradeQueryResponse
     */
    invoiceAmount?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AlipayTradeQueryResponse
     */
    mdiscountAmount?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AlipayTradeQueryResponse
     */
    medicalInsuranceInfo?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AlipayTradeQueryResponse
     */
    openId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AlipayTradeQueryResponse
     */
    outTradeNo?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AlipayTradeQueryResponse
     */
    passbackParams?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AlipayTradeQueryResponse
     */
    payAmount?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AlipayTradeQueryResponse
     */
    payCurrency?: string | null;
    /**
     * 
     * @type {Array<PaymentInfoWithId>}
     * @memberof AlipayTradeQueryResponse
     */
    paymentInfoWithIdList?: Array<PaymentInfoWithId> | null;
    /**
     * 
     * @type {string}
     * @memberof AlipayTradeQueryResponse
     */
    periodScene?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AlipayTradeQueryResponse
     */
    pointAmount?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AlipayTradeQueryResponse
     */
    preAuthPayAmount?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AlipayTradeQueryResponse
     */
    receiptAmount?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AlipayTradeQueryResponse
     */
    receiptCurrencyType?: string | null;
    /**
     * 
     * @type {Array<GoodsDetail>}
     * @memberof AlipayTradeQueryResponse
     */
    reqGoodsDetail?: Array<GoodsDetail> | null;
    /**
     * 
     * @type {string}
     * @memberof AlipayTradeQueryResponse
     */
    sendPayDate?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AlipayTradeQueryResponse
     */
    settleAmount?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AlipayTradeQueryResponse
     */
    settleCurrency?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AlipayTradeQueryResponse
     */
    settleTransRate?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AlipayTradeQueryResponse
     */
    settlementId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AlipayTradeQueryResponse
     */
    storeId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AlipayTradeQueryResponse
     */
    storeName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AlipayTradeQueryResponse
     */
    subject?: string | null;
    /**
     * 
     * @type {TapPayInfo}
     * @memberof AlipayTradeQueryResponse
     */
    tapPayInfo?: TapPayInfo;
    /**
     * 
     * @type {string}
     * @memberof AlipayTradeQueryResponse
     */
    terminalId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AlipayTradeQueryResponse
     */
    totalAmount?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AlipayTradeQueryResponse
     */
    tradeNo?: string | null;
    /**
     * 
     * @type {TradeSettleInfo}
     * @memberof AlipayTradeQueryResponse
     */
    tradeSettleInfo?: TradeSettleInfo;
    /**
     * 
     * @type {string}
     * @memberof AlipayTradeQueryResponse
     */
    tradeStatus?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AlipayTradeQueryResponse
     */
    transCurrency?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AlipayTradeQueryResponse
     */
    transPayRate?: string | null;
    /**
     * 
     * @type {Array<VoucherDetail>}
     * @memberof AlipayTradeQueryResponse
     */
    voucherDetailList?: Array<VoucherDetail> | null;
}

/**
 * Check if a given object implements the AlipayTradeQueryResponse interface.
 */
export function instanceOfAlipayTradeQueryResponse(value: object): value is AlipayTradeQueryResponse {
    return true;
}

export function AlipayTradeQueryResponseFromJSON(json: any): AlipayTradeQueryResponse {
    return AlipayTradeQueryResponseFromJSONTyped(json, false);
}

export function AlipayTradeQueryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AlipayTradeQueryResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'msg': json['msg'] == null ? undefined : json['msg'],
        'subCode': json['subCode'] == null ? undefined : json['subCode'],
        'subMsg': json['subMsg'] == null ? undefined : json['subMsg'],
        'isError': json['isError'] == null ? undefined : json['isError'],
        'additionalStatus': json['additionalStatus'] == null ? undefined : json['additionalStatus'],
        'alipayStoreId': json['alipayStoreId'] == null ? undefined : json['alipayStoreId'],
        'alipaySubMerchantId': json['alipaySubMerchantId'] == null ? undefined : json['alipaySubMerchantId'],
        'asyncPayApplyStatus': json['asyncPayApplyStatus'] == null ? undefined : json['asyncPayApplyStatus'],
        'authTradePayMode': json['authTradePayMode'] == null ? undefined : json['authTradePayMode'],
        'bizSettleMode': json['bizSettleMode'] == null ? undefined : json['bizSettleMode'],
        'bkagentRespInfo': json['bkagentRespInfo'] == null ? undefined : BkAgentRespInfoFromJSON(json['bkagentRespInfo']),
        'body': json['body'] == null ? undefined : json['body'],
        'buyerLogonId': json['buyerLogonId'] == null ? undefined : json['buyerLogonId'],
        'buyerOpenId': json['buyerOpenId'] == null ? undefined : json['buyerOpenId'],
        'buyerPayAmount': json['buyerPayAmount'] == null ? undefined : json['buyerPayAmount'],
        'buyerUserId': json['buyerUserId'] == null ? undefined : json['buyerUserId'],
        'buyerUserName': json['buyerUserName'] == null ? undefined : json['buyerUserName'],
        'buyerUserType': json['buyerUserType'] == null ? undefined : json['buyerUserType'],
        'cashierType': json['cashierType'] == null ? undefined : json['cashierType'],
        'chargeAmount': json['chargeAmount'] == null ? undefined : json['chargeAmount'],
        'chargeFlags': json['chargeFlags'] == null ? undefined : json['chargeFlags'],
        'chargeInfoList': json['chargeInfoList'] == null ? undefined : ((json['chargeInfoList'] as Array<any>).map(ChargeInfoFromJSON)),
        'creditBizOrderId': json['creditBizOrderId'] == null ? undefined : json['creditBizOrderId'],
        'creditPayMode': json['creditPayMode'] == null ? undefined : json['creditPayMode'],
        'discountAmount': json['discountAmount'] == null ? undefined : json['discountAmount'],
        'discountGoodsDetail': json['discountGoodsDetail'] == null ? undefined : json['discountGoodsDetail'],
        'enterprisePayInfo': json['enterprisePayInfo'] == null ? undefined : EnterprisePayInfoFromJSON(json['enterprisePayInfo']),
        'extInfos': json['extInfos'] == null ? undefined : json['extInfos'],
        'fulfillmentDetailList': json['fulfillmentDetailList'] == null ? undefined : ((json['fulfillmentDetailList'] as Array<any>).map(FulfillmentDetailFromJSON)),
        'fundBillList': json['fundBillList'] == null ? undefined : ((json['fundBillList'] as Array<any>).map(TradeFundBillFromJSON)),
        'hbFqPayInfo': json['hbFqPayInfo'] == null ? undefined : HbFqPayInfoFromJSON(json['hbFqPayInfo']),
        'hybAmount': json['hybAmount'] == null ? undefined : json['hybAmount'],
        'industrySepcDetail': json['industrySepcDetail'] == null ? undefined : json['industrySepcDetail'],
        'industrySepcDetailAcc': json['industrySepcDetailAcc'] == null ? undefined : json['industrySepcDetailAcc'],
        'industrySepcDetailGov': json['industrySepcDetailGov'] == null ? undefined : json['industrySepcDetailGov'],
        'intactChargeInfoList': json['intactChargeInfoList'] == null ? undefined : ((json['intactChargeInfoList'] as Array<any>).map(IntactChargeInfoFromJSON)),
        'invoiceAmount': json['invoiceAmount'] == null ? undefined : json['invoiceAmount'],
        'mdiscountAmount': json['mdiscountAmount'] == null ? undefined : json['mdiscountAmount'],
        'medicalInsuranceInfo': json['medicalInsuranceInfo'] == null ? undefined : json['medicalInsuranceInfo'],
        'openId': json['openId'] == null ? undefined : json['openId'],
        'outTradeNo': json['outTradeNo'] == null ? undefined : json['outTradeNo'],
        'passbackParams': json['passbackParams'] == null ? undefined : json['passbackParams'],
        'payAmount': json['payAmount'] == null ? undefined : json['payAmount'],
        'payCurrency': json['payCurrency'] == null ? undefined : json['payCurrency'],
        'paymentInfoWithIdList': json['paymentInfoWithIdList'] == null ? undefined : ((json['paymentInfoWithIdList'] as Array<any>).map(PaymentInfoWithIdFromJSON)),
        'periodScene': json['periodScene'] == null ? undefined : json['periodScene'],
        'pointAmount': json['pointAmount'] == null ? undefined : json['pointAmount'],
        'preAuthPayAmount': json['preAuthPayAmount'] == null ? undefined : json['preAuthPayAmount'],
        'receiptAmount': json['receiptAmount'] == null ? undefined : json['receiptAmount'],
        'receiptCurrencyType': json['receiptCurrencyType'] == null ? undefined : json['receiptCurrencyType'],
        'reqGoodsDetail': json['reqGoodsDetail'] == null ? undefined : ((json['reqGoodsDetail'] as Array<any>).map(GoodsDetailFromJSON)),
        'sendPayDate': json['sendPayDate'] == null ? undefined : json['sendPayDate'],
        'settleAmount': json['settleAmount'] == null ? undefined : json['settleAmount'],
        'settleCurrency': json['settleCurrency'] == null ? undefined : json['settleCurrency'],
        'settleTransRate': json['settleTransRate'] == null ? undefined : json['settleTransRate'],
        'settlementId': json['settlementId'] == null ? undefined : json['settlementId'],
        'storeId': json['storeId'] == null ? undefined : json['storeId'],
        'storeName': json['storeName'] == null ? undefined : json['storeName'],
        'subject': json['subject'] == null ? undefined : json['subject'],
        'tapPayInfo': json['tapPayInfo'] == null ? undefined : TapPayInfoFromJSON(json['tapPayInfo']),
        'terminalId': json['terminalId'] == null ? undefined : json['terminalId'],
        'totalAmount': json['totalAmount'] == null ? undefined : json['totalAmount'],
        'tradeNo': json['tradeNo'] == null ? undefined : json['tradeNo'],
        'tradeSettleInfo': json['tradeSettleInfo'] == null ? undefined : TradeSettleInfoFromJSON(json['tradeSettleInfo']),
        'tradeStatus': json['tradeStatus'] == null ? undefined : json['tradeStatus'],
        'transCurrency': json['transCurrency'] == null ? undefined : json['transCurrency'],
        'transPayRate': json['transPayRate'] == null ? undefined : json['transPayRate'],
        'voucherDetailList': json['voucherDetailList'] == null ? undefined : ((json['voucherDetailList'] as Array<any>).map(VoucherDetailFromJSON)),
    };
}

export function AlipayTradeQueryResponseToJSON(json: any): AlipayTradeQueryResponse {
    return AlipayTradeQueryResponseToJSONTyped(json, false);
}

export function AlipayTradeQueryResponseToJSONTyped(value?: Omit<AlipayTradeQueryResponse, 'isError'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'msg': value['msg'],
        'subCode': value['subCode'],
        'subMsg': value['subMsg'],
        'additionalStatus': value['additionalStatus'],
        'alipayStoreId': value['alipayStoreId'],
        'alipaySubMerchantId': value['alipaySubMerchantId'],
        'asyncPayApplyStatus': value['asyncPayApplyStatus'],
        'authTradePayMode': value['authTradePayMode'],
        'bizSettleMode': value['bizSettleMode'],
        'bkagentRespInfo': BkAgentRespInfoToJSON(value['bkagentRespInfo']),
        'body': value['body'],
        'buyerLogonId': value['buyerLogonId'],
        'buyerOpenId': value['buyerOpenId'],
        'buyerPayAmount': value['buyerPayAmount'],
        'buyerUserId': value['buyerUserId'],
        'buyerUserName': value['buyerUserName'],
        'buyerUserType': value['buyerUserType'],
        'cashierType': value['cashierType'],
        'chargeAmount': value['chargeAmount'],
        'chargeFlags': value['chargeFlags'],
        'chargeInfoList': value['chargeInfoList'] == null ? undefined : ((value['chargeInfoList'] as Array<any>).map(ChargeInfoToJSON)),
        'creditBizOrderId': value['creditBizOrderId'],
        'creditPayMode': value['creditPayMode'],
        'discountAmount': value['discountAmount'],
        'discountGoodsDetail': value['discountGoodsDetail'],
        'enterprisePayInfo': EnterprisePayInfoToJSON(value['enterprisePayInfo']),
        'extInfos': value['extInfos'],
        'fulfillmentDetailList': value['fulfillmentDetailList'] == null ? undefined : ((value['fulfillmentDetailList'] as Array<any>).map(FulfillmentDetailToJSON)),
        'fundBillList': value['fundBillList'] == null ? undefined : ((value['fundBillList'] as Array<any>).map(TradeFundBillToJSON)),
        'hbFqPayInfo': HbFqPayInfoToJSON(value['hbFqPayInfo']),
        'hybAmount': value['hybAmount'],
        'industrySepcDetail': value['industrySepcDetail'],
        'industrySepcDetailAcc': value['industrySepcDetailAcc'],
        'industrySepcDetailGov': value['industrySepcDetailGov'],
        'intactChargeInfoList': value['intactChargeInfoList'] == null ? undefined : ((value['intactChargeInfoList'] as Array<any>).map(IntactChargeInfoToJSON)),
        'invoiceAmount': value['invoiceAmount'],
        'mdiscountAmount': value['mdiscountAmount'],
        'medicalInsuranceInfo': value['medicalInsuranceInfo'],
        'openId': value['openId'],
        'outTradeNo': value['outTradeNo'],
        'passbackParams': value['passbackParams'],
        'payAmount': value['payAmount'],
        'payCurrency': value['payCurrency'],
        'paymentInfoWithIdList': value['paymentInfoWithIdList'] == null ? undefined : ((value['paymentInfoWithIdList'] as Array<any>).map(PaymentInfoWithIdToJSON)),
        'periodScene': value['periodScene'],
        'pointAmount': value['pointAmount'],
        'preAuthPayAmount': value['preAuthPayAmount'],
        'receiptAmount': value['receiptAmount'],
        'receiptCurrencyType': value['receiptCurrencyType'],
        'reqGoodsDetail': value['reqGoodsDetail'] == null ? undefined : ((value['reqGoodsDetail'] as Array<any>).map(GoodsDetailToJSON)),
        'sendPayDate': value['sendPayDate'],
        'settleAmount': value['settleAmount'],
        'settleCurrency': value['settleCurrency'],
        'settleTransRate': value['settleTransRate'],
        'settlementId': value['settlementId'],
        'storeId': value['storeId'],
        'storeName': value['storeName'],
        'subject': value['subject'],
        'tapPayInfo': TapPayInfoToJSON(value['tapPayInfo']),
        'terminalId': value['terminalId'],
        'totalAmount': value['totalAmount'],
        'tradeNo': value['tradeNo'],
        'tradeSettleInfo': TradeSettleInfoToJSON(value['tradeSettleInfo']),
        'tradeStatus': value['tradeStatus'],
        'transCurrency': value['transCurrency'],
        'transPayRate': value['transPayRate'],
        'voucherDetailList': value['voucherDetailList'] == null ? undefined : ((value['voucherDetailList'] as Array<any>).map(VoucherDetailToJSON)),
    };
}

