/* tslint:disable */
/* eslint-disable */
/**
 * 全部  API 文档
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 应用
 * @export
 * @interface App
 */
export interface App {
    /**
     * 唯一标识符
     * @type {number}
     * @memberof App
     */
    id?: number;
    /**
     * 用户 ID
     * @type {number}
     * @memberof App
     */
    userID?: number;
    /**
     * 项目 ID
     * @type {number}
     * @memberof App
     */
    projectID?: number;
    /**
     * 网站默认域名
     * @type {string}
     * @memberof App
     */
    website?: string | null;
    /**
     * 名称
     * @type {string}
     * @memberof App
     */
    name?: string | null;
    /**
     * Logo
     * @type {string}
     * @memberof App
     */
    logo?: string | null;
    /**
     * 描述
     * @type {string}
     * @memberof App
     */
    description?: string | null;
    /**
     * 标签
     * @type {string}
     * @memberof App
     */
    tags?: string | null;
    /**
     * 应用公钥
     * @type {string}
     * @memberof App
     */
    appKey?: string | null;
    /**
     * 应用私密密钥
     * @type {string}
     * @memberof App
     */
    appSecret?: string | null;
    /**
     * 客户端密钥
     * @type {string}
     * @memberof App
     */
    clientSecret?: string | null;
    /**
     * SSH公钥
     * @type {string}
     * @memberof App
     */
    sshPublickey?: string | null;
    /**
     * 是否共享
     * @type {boolean}
     * @memberof App
     */
    share?: boolean;
    /**
     * 创建时间
     * @type {Date}
     * @memberof App
     */
    createDate?: Date;
    /**
     * 最后更新时间
     * @type {Date}
     * @memberof App
     */
    lastUpdate?: Date;
    /**
     * 是否显示
     * @type {boolean}
     * @memberof App
     */
    show?: boolean;
    /**
     * 显示索引
     * @type {number}
     * @memberof App
     */
    showIndex?: number;
}

/**
 * Check if a given object implements the App interface.
 */
export function instanceOfApp(value: object): value is App {
    return true;
}

export function AppFromJSON(json: any): App {
    return AppFromJSONTyped(json, false);
}

export function AppFromJSONTyped(json: any, ignoreDiscriminator: boolean): App {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'userID': json['userID'] == null ? undefined : json['userID'],
        'projectID': json['projectID'] == null ? undefined : json['projectID'],
        'website': json['website'] == null ? undefined : json['website'],
        'name': json['name'] == null ? undefined : json['name'],
        'logo': json['logo'] == null ? undefined : json['logo'],
        'description': json['description'] == null ? undefined : json['description'],
        'tags': json['tags'] == null ? undefined : json['tags'],
        'appKey': json['appKey'] == null ? undefined : json['appKey'],
        'appSecret': json['appSecret'] == null ? undefined : json['appSecret'],
        'clientSecret': json['clientSecret'] == null ? undefined : json['clientSecret'],
        'sshPublickey': json['sshPublickey'] == null ? undefined : json['sshPublickey'],
        'share': json['share'] == null ? undefined : json['share'],
        'createDate': json['createDate'] == null ? undefined : (new Date(json['createDate'])),
        'lastUpdate': json['lastUpdate'] == null ? undefined : (new Date(json['lastUpdate'])),
        'show': json['show'] == null ? undefined : json['show'],
        'showIndex': json['showIndex'] == null ? undefined : json['showIndex'],
    };
}

export function AppToJSON(json: any): App {
    return AppToJSONTyped(json, false);
}

export function AppToJSONTyped(value?: App | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'userID': value['userID'],
        'projectID': value['projectID'],
        'website': value['website'],
        'name': value['name'],
        'logo': value['logo'],
        'description': value['description'],
        'tags': value['tags'],
        'appKey': value['appKey'],
        'appSecret': value['appSecret'],
        'clientSecret': value['clientSecret'],
        'sshPublickey': value['sshPublickey'],
        'share': value['share'],
        'createDate': value['createDate'] == null ? undefined : ((value['createDate']).toISOString()),
        'lastUpdate': value['lastUpdate'] == null ? undefined : ((value['lastUpdate']).toISOString()),
        'show': value['show'],
        'showIndex': value['showIndex'],
    };
}

