/* tslint:disable */
/* eslint-disable */
/**
 * 用户全部 API 文档
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AppInfoItem } from './AppInfoItem';
import {
    AppInfoItemFromJSON,
    AppInfoItemFromJSONTyped,
    AppInfoItemToJSON,
    AppInfoItemToJSONTyped,
} from './AppInfoItem';
import type { AppProperty } from './AppProperty';
import {
    AppPropertyFromJSON,
    AppPropertyFromJSONTyped,
    AppPropertyToJSON,
    AppPropertyToJSONTyped,
} from './AppProperty';

/**
 * 
 * @export
 * @interface AppInfoResult
 */
export interface AppInfoResult {
    /**
     * 
     * @type {AppInfoItem}
     * @memberof AppInfoResult
     */
    info?: AppInfoItem;
    /**
     * 
     * @type {Array<AppProperty>}
     * @memberof AppInfoResult
     */
    props?: Array<AppProperty> | null;
}

/**
 * Check if a given object implements the AppInfoResult interface.
 */
export function instanceOfAppInfoResult(value: object): value is AppInfoResult {
    return true;
}

export function AppInfoResultFromJSON(json: any): AppInfoResult {
    return AppInfoResultFromJSONTyped(json, false);
}

export function AppInfoResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppInfoResult {
    if (json == null) {
        return json;
    }
    return {
        
        'info': json['info'] == null ? undefined : AppInfoItemFromJSON(json['info']),
        'props': json['props'] == null ? undefined : ((json['props'] as Array<any>).map(AppPropertyFromJSON)),
    };
}

export function AppInfoResultToJSON(json: any): AppInfoResult {
    return AppInfoResultToJSONTyped(json, false);
}

export function AppInfoResultToJSONTyped(value?: AppInfoResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'info': AppInfoItemToJSON(value['info']),
        'props': value['props'] == null ? undefined : ((value['props'] as Array<any>).map(AppPropertyToJSON)),
    };
}

