/* tslint:disable */
/* eslint-disable */
/**
 * 全部  API 文档
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AppListResult } from './AppListResult';
import {
    AppListResultFromJSON,
    AppListResultFromJSONTyped,
    AppListResultToJSON,
    AppListResultToJSONTyped,
} from './AppListResult';

/**
 * 
 * @export
 * @interface AppListResultApiResponse
 */
export interface AppListResultApiResponse {
    /**
     * 状态码
     * @type {number}
     * @memberof AppListResultApiResponse
     */
    code?: number;
    /**
     * 
     * @type {AppListResult}
     * @memberof AppListResultApiResponse
     */
    data?: AppListResult;
    /**
     * 错误信息
     * @type {string}
     * @memberof AppListResultApiResponse
     */
    error?: string | null;
}

/**
 * Check if a given object implements the AppListResultApiResponse interface.
 */
export function instanceOfAppListResultApiResponse(value: object): value is AppListResultApiResponse {
    return true;
}

export function AppListResultApiResponseFromJSON(json: any): AppListResultApiResponse {
    return AppListResultApiResponseFromJSONTyped(json, false);
}

export function AppListResultApiResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppListResultApiResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'data': json['data'] == null ? undefined : AppListResultFromJSON(json['data']),
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function AppListResultApiResponseToJSON(json: any): AppListResultApiResponse {
    return AppListResultApiResponseToJSONTyped(json, false);
}

export function AppListResultApiResponseToJSONTyped(value?: AppListResultApiResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'data': AppListResultToJSON(value['data']),
        'error': value['error'],
    };
}

