/* tslint:disable */
/* eslint-disable */
/**
 * 全部  API 文档
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AppPostResult
 */
export interface AppPostResult {
    /**
     * 
     * @type {number}
     * @memberof AppPostResult
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof AppPostResult
     */
    serverPath?: string | null;
}

/**
 * Check if a given object implements the AppPostResult interface.
 */
export function instanceOfAppPostResult(value: object): value is AppPostResult {
    return true;
}

export function AppPostResultFromJSON(json: any): AppPostResult {
    return AppPostResultFromJSONTyped(json, false);
}

export function AppPostResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppPostResult {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'serverPath': json['serverPath'] == null ? undefined : json['serverPath'],
    };
}

export function AppPostResultToJSON(json: any): AppPostResult {
    return AppPostResultToJSONTyped(json, false);
}

export function AppPostResultToJSONTyped(value?: AppPostResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'serverPath': value['serverPath'],
    };
}

