/* tslint:disable */
/* eslint-disable */
/**
 * 全部  API 文档
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AppSettingItemPostResult
 */
export interface AppSettingItemPostResult {
    /**
     * 
     * @type {number}
     * @memberof AppSettingItemPostResult
     */
    id?: number;
}

/**
 * Check if a given object implements the AppSettingItemPostResult interface.
 */
export function instanceOfAppSettingItemPostResult(value: object): value is AppSettingItemPostResult {
    return true;
}

export function AppSettingItemPostResultFromJSON(json: any): AppSettingItemPostResult {
    return AppSettingItemPostResultFromJSONTyped(json, false);
}

export function AppSettingItemPostResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppSettingItemPostResult {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function AppSettingItemPostResultToJSON(json: any): AppSettingItemPostResult {
    return AppSettingItemPostResultToJSONTyped(json, false);
}

export function AppSettingItemPostResultToJSONTyped(value?: AppSettingItemPostResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
    };
}

