/* tslint:disable */
/* eslint-disable */
/**
 * 全部  API 文档
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AppSettingSettingPostResult } from './AppSettingSettingPostResult';
import {
    AppSettingSettingPostResultFromJSON,
    AppSettingSettingPostResultFromJSONTyped,
    AppSettingSettingPostResultToJSON,
    AppSettingSettingPostResultToJSONTyped,
} from './AppSettingSettingPostResult';

/**
 * 
 * @export
 * @interface AppSettingSettingPostResultApiResponse
 */
export interface AppSettingSettingPostResultApiResponse {
    /**
     * 状态码
     * @type {number}
     * @memberof AppSettingSettingPostResultApiResponse
     */
    code?: number;
    /**
     * 
     * @type {AppSettingSettingPostResult}
     * @memberof AppSettingSettingPostResultApiResponse
     */
    data?: AppSettingSettingPostResult;
    /**
     * 错误信息
     * @type {string}
     * @memberof AppSettingSettingPostResultApiResponse
     */
    error?: string | null;
}

/**
 * Check if a given object implements the AppSettingSettingPostResultApiResponse interface.
 */
export function instanceOfAppSettingSettingPostResultApiResponse(value: object): value is AppSettingSettingPostResultApiResponse {
    return true;
}

export function AppSettingSettingPostResultApiResponseFromJSON(json: any): AppSettingSettingPostResultApiResponse {
    return AppSettingSettingPostResultApiResponseFromJSONTyped(json, false);
}

export function AppSettingSettingPostResultApiResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppSettingSettingPostResultApiResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'data': json['data'] == null ? undefined : AppSettingSettingPostResultFromJSON(json['data']),
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function AppSettingSettingPostResultApiResponseToJSON(json: any): AppSettingSettingPostResultApiResponse {
    return AppSettingSettingPostResultApiResponseToJSONTyped(json, false);
}

export function AppSettingSettingPostResultApiResponseToJSONTyped(value?: AppSettingSettingPostResultApiResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'data': AppSettingSettingPostResultToJSON(value['data']),
        'error': value['error'],
    };
}

