/* tslint:disable */
/* eslint-disable */
/**
 * 用户全部 API 文档
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AppUserResetPhoneRequest
 */
export interface AppUserResetPhoneRequest {
    /**
     * 手机号码
     * @type {string}
     * @memberof AppUserResetPhoneRequest
     */
    phone?: string | null;
    /**
     * 手机验证码
     * @type {string}
     * @memberof AppUserResetPhoneRequest
     */
    code: string;
}

/**
 * Check if a given object implements the AppUserResetPhoneRequest interface.
 */
export function instanceOfAppUserResetPhoneRequest(value: object): value is AppUserResetPhoneRequest {
    if (!('code' in value) || value['code'] === undefined) return false;
    return true;
}

export function AppUserResetPhoneRequestFromJSON(json: any): AppUserResetPhoneRequest {
    return AppUserResetPhoneRequestFromJSONTyped(json, false);
}

export function AppUserResetPhoneRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppUserResetPhoneRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'phone': json['phone'] == null ? undefined : json['phone'],
        'code': json['code'],
    };
}

export function AppUserResetPhoneRequestToJSON(json: any): AppUserResetPhoneRequest {
    return AppUserResetPhoneRequestToJSONTyped(json, false);
}

export function AppUserResetPhoneRequestToJSONTyped(value?: AppUserResetPhoneRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'phone': value['phone'],
        'code': value['code'],
    };
}

