/* tslint:disable */
/* eslint-disable */
/**
 * 用户全部 API 文档
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AuthorizeResult } from './AuthorizeResult';
import {
    AuthorizeResultFromJSON,
    AuthorizeResultFromJSONTyped,
    AuthorizeResultToJSON,
    AuthorizeResultToJSONTyped,
} from './AuthorizeResult';

/**
 * 
 * @export
 * @interface AuthorizeResultApiResponse
 */
export interface AuthorizeResultApiResponse {
    /**
     * 状态码
     * @type {number}
     * @memberof AuthorizeResultApiResponse
     */
    code?: number;
    /**
     * 
     * @type {AuthorizeResult}
     * @memberof AuthorizeResultApiResponse
     */
    data?: AuthorizeResult;
    /**
     * 错误信息
     * @type {string}
     * @memberof AuthorizeResultApiResponse
     */
    error?: string | null;
}

/**
 * Check if a given object implements the AuthorizeResultApiResponse interface.
 */
export function instanceOfAuthorizeResultApiResponse(value: object): value is AuthorizeResultApiResponse {
    return true;
}

export function AuthorizeResultApiResponseFromJSON(json: any): AuthorizeResultApiResponse {
    return AuthorizeResultApiResponseFromJSONTyped(json, false);
}

export function AuthorizeResultApiResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthorizeResultApiResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'data': json['data'] == null ? undefined : AuthorizeResultFromJSON(json['data']),
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function AuthorizeResultApiResponseToJSON(json: any): AuthorizeResultApiResponse {
    return AuthorizeResultApiResponseToJSONTyped(json, false);
}

export function AuthorizeResultApiResponseToJSONTyped(value?: AuthorizeResultApiResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'data': AuthorizeResultToJSON(value['data']),
        'error': value['error'],
    };
}

