/* tslint:disable */
/* eslint-disable */
/**
 * 全部  API 文档
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AuthorizePolicy } from './AuthorizePolicy';
import {
    AuthorizePolicyFromJSON,
    AuthorizePolicyFromJSONTyped,
    AuthorizePolicyToJSON,
    AuthorizePolicyToJSONTyped,
} from './AuthorizePolicy';

/**
 * 
 * @export
 * @interface AuthorizePolicyApiResponse
 */
export interface AuthorizePolicyApiResponse {
    /**
     * 状态码
     * @type {number}
     * @memberof AuthorizePolicyApiResponse
     */
    code?: number;
    /**
     * 
     * @type {AuthorizePolicy}
     * @memberof AuthorizePolicyApiResponse
     */
    data?: AuthorizePolicy;
    /**
     * 错误信息
     * @type {string}
     * @memberof AuthorizePolicyApiResponse
     */
    error?: string | null;
}

/**
 * Check if a given object implements the AuthorizePolicyApiResponse interface.
 */
export function instanceOfAuthorizePolicyApiResponse(value: object): value is AuthorizePolicyApiResponse {
    return true;
}

export function AuthorizePolicyApiResponseFromJSON(json: any): AuthorizePolicyApiResponse {
    return AuthorizePolicyApiResponseFromJSONTyped(json, false);
}

export function AuthorizePolicyApiResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthorizePolicyApiResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'data': json['data'] == null ? undefined : AuthorizePolicyFromJSON(json['data']),
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function AuthorizePolicyApiResponseToJSON(json: any): AuthorizePolicyApiResponse {
    return AuthorizePolicyApiResponseToJSONTyped(json, false);
}

export function AuthorizePolicyApiResponseToJSONTyped(value?: AuthorizePolicyApiResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'data': AuthorizePolicyToJSON(value['data']),
        'error': value['error'],
    };
}

