/* tslint:disable */
/* eslint-disable */
/**
 * 用户全部 API 文档
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateOrderRequest
 */
export interface CreateOrderRequest {
    /**
     * 
     * @type {number}
     * @memberof CreateOrderRequest
     */
    amount: number;
    /**
     * 
     * @type {string}
     * @memberof CreateOrderRequest
     */
    productName: string;
    /**
     * 
     * @type {string}
     * @memberof CreateOrderRequest
     */
    productType: string;
    /**
     * 
     * @type {string}
     * @memberof CreateOrderRequest
     */
    productID: string;
}

/**
 * Check if a given object implements the CreateOrderRequest interface.
 */
export function instanceOfCreateOrderRequest(value: object): value is CreateOrderRequest {
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('productName' in value) || value['productName'] === undefined) return false;
    if (!('productType' in value) || value['productType'] === undefined) return false;
    if (!('productID' in value) || value['productID'] === undefined) return false;
    return true;
}

export function CreateOrderRequestFromJSON(json: any): CreateOrderRequest {
    return CreateOrderRequestFromJSONTyped(json, false);
}

export function CreateOrderRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateOrderRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'],
        'productName': json['productName'],
        'productType': json['productType'],
        'productID': json['productID'],
    };
}

export function CreateOrderRequestToJSON(json: any): CreateOrderRequest {
    return CreateOrderRequestToJSONTyped(json, false);
}

export function CreateOrderRequestToJSONTyped(value?: CreateOrderRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount': value['amount'],
        'productName': value['productName'],
        'productType': value['productType'],
        'productID': value['productID'],
    };
}

