/* tslint:disable */
/* eslint-disable */
/**
 * 用户全部 API 文档
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateOrderResult } from './CreateOrderResult';
import {
    CreateOrderResultFromJSON,
    CreateOrderResultFromJSONTyped,
    CreateOrderResultToJSON,
    CreateOrderResultToJSONTyped,
} from './CreateOrderResult';

/**
 * 
 * @export
 * @interface CreateOrderResultApiResponse
 */
export interface CreateOrderResultApiResponse {
    /**
     * 状态码
     * @type {number}
     * @memberof CreateOrderResultApiResponse
     */
    code?: number;
    /**
     * 
     * @type {CreateOrderResult}
     * @memberof CreateOrderResultApiResponse
     */
    data?: CreateOrderResult;
    /**
     * 错误信息
     * @type {string}
     * @memberof CreateOrderResultApiResponse
     */
    error?: string | null;
}

/**
 * Check if a given object implements the CreateOrderResultApiResponse interface.
 */
export function instanceOfCreateOrderResultApiResponse(value: object): value is CreateOrderResultApiResponse {
    return true;
}

export function CreateOrderResultApiResponseFromJSON(json: any): CreateOrderResultApiResponse {
    return CreateOrderResultApiResponseFromJSONTyped(json, false);
}

export function CreateOrderResultApiResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateOrderResultApiResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'data': json['data'] == null ? undefined : CreateOrderResultFromJSON(json['data']),
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function CreateOrderResultApiResponseToJSON(json: any): CreateOrderResultApiResponse {
    return CreateOrderResultApiResponseToJSONTyped(json, false);
}

export function CreateOrderResultApiResponseToJSONTyped(value?: CreateOrderResultApiResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'data': CreateOrderResultToJSON(value['data']),
        'error': value['error'],
    };
}

