/* tslint:disable */
/* eslint-disable */
/**
 * 用户全部 API 文档
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateOrderResult
 */
export interface CreateOrderResult {
    /**
     * 
     * @type {number}
     * @memberof CreateOrderResult
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof CreateOrderResult
     */
    orderNo?: string | null;
}

/**
 * Check if a given object implements the CreateOrderResult interface.
 */
export function instanceOfCreateOrderResult(value: object): value is CreateOrderResult {
    return true;
}

export function CreateOrderResultFromJSON(json: any): CreateOrderResult {
    return CreateOrderResultFromJSONTyped(json, false);
}

export function CreateOrderResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateOrderResult {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'orderNo': json['orderNo'] == null ? undefined : json['orderNo'],
    };
}

export function CreateOrderResultToJSON(json: any): CreateOrderResult {
    return CreateOrderResultToJSONTyped(json, false);
}

export function CreateOrderResultToJSONTyped(value?: CreateOrderResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'orderNo': value['orderNo'],
    };
}

