/* tslint:disable */
/* eslint-disable */
/**
 * 用户全部 API 文档
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CurrencyStatsItem
 */
export interface CurrencyStatsItem {
    /**
     * 
     * @type {string}
     * @memberof CurrencyStatsItem
     */
    currencyType?: string | null;
    /**
     * 
     * @type {number}
     * @memberof CurrencyStatsItem
     */
    rechargeAmount?: number;
    /**
     * 
     * @type {number}
     * @memberof CurrencyStatsItem
     */
    rechargeCount?: number;
    /**
     * 
     * @type {number}
     * @memberof CurrencyStatsItem
     */
    consumeAmount?: number;
    /**
     * 
     * @type {number}
     * @memberof CurrencyStatsItem
     */
    consumeCount?: number;
    /**
     * 
     * @type {number}
     * @memberof CurrencyStatsItem
     */
    exchangeInAmount?: number;
    /**
     * 
     * @type {number}
     * @memberof CurrencyStatsItem
     */
    exchangeOutAmount?: number;
    /**
     * 
     * @type {number}
     * @memberof CurrencyStatsItem
     */
    exchangeCount?: number;
    /**
     * 
     * @type {number}
     * @memberof CurrencyStatsItem
     */
    transferInAmount?: number;
    /**
     * 
     * @type {number}
     * @memberof CurrencyStatsItem
     */
    transferOutAmount?: number;
    /**
     * 
     * @type {number}
     * @memberof CurrencyStatsItem
     */
    transferCount?: number;
    /**
     * 
     * @type {number}
     * @memberof CurrencyStatsItem
     */
    netChange?: number;
    /**
     * 
     * @type {number}
     * @memberof CurrencyStatsItem
     */
    transactionCount?: number;
}

/**
 * Check if a given object implements the CurrencyStatsItem interface.
 */
export function instanceOfCurrencyStatsItem(value: object): value is CurrencyStatsItem {
    return true;
}

export function CurrencyStatsItemFromJSON(json: any): CurrencyStatsItem {
    return CurrencyStatsItemFromJSONTyped(json, false);
}

export function CurrencyStatsItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): CurrencyStatsItem {
    if (json == null) {
        return json;
    }
    return {
        
        'currencyType': json['currencyType'] == null ? undefined : json['currencyType'],
        'rechargeAmount': json['rechargeAmount'] == null ? undefined : json['rechargeAmount'],
        'rechargeCount': json['rechargeCount'] == null ? undefined : json['rechargeCount'],
        'consumeAmount': json['consumeAmount'] == null ? undefined : json['consumeAmount'],
        'consumeCount': json['consumeCount'] == null ? undefined : json['consumeCount'],
        'exchangeInAmount': json['exchangeInAmount'] == null ? undefined : json['exchangeInAmount'],
        'exchangeOutAmount': json['exchangeOutAmount'] == null ? undefined : json['exchangeOutAmount'],
        'exchangeCount': json['exchangeCount'] == null ? undefined : json['exchangeCount'],
        'transferInAmount': json['transferInAmount'] == null ? undefined : json['transferInAmount'],
        'transferOutAmount': json['transferOutAmount'] == null ? undefined : json['transferOutAmount'],
        'transferCount': json['transferCount'] == null ? undefined : json['transferCount'],
        'netChange': json['netChange'] == null ? undefined : json['netChange'],
        'transactionCount': json['transactionCount'] == null ? undefined : json['transactionCount'],
    };
}

export function CurrencyStatsItemToJSON(json: any): CurrencyStatsItem {
    return CurrencyStatsItemToJSONTyped(json, false);
}

export function CurrencyStatsItemToJSONTyped(value?: CurrencyStatsItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'currencyType': value['currencyType'],
        'rechargeAmount': value['rechargeAmount'],
        'rechargeCount': value['rechargeCount'],
        'consumeAmount': value['consumeAmount'],
        'consumeCount': value['consumeCount'],
        'exchangeInAmount': value['exchangeInAmount'],
        'exchangeOutAmount': value['exchangeOutAmount'],
        'exchangeCount': value['exchangeCount'],
        'transferInAmount': value['transferInAmount'],
        'transferOutAmount': value['transferOutAmount'],
        'transferCount': value['transferCount'],
        'netChange': value['netChange'],
        'transactionCount': value['transactionCount'],
    };
}

