/* tslint:disable */
/* eslint-disable */
/**
 * 全部  API 文档
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EmailSignInRequest
 */
export interface EmailSignInRequest {
    /**
     * 
     * @type {string}
     * @memberof EmailSignInRequest
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof EmailSignInRequest
     */
    verifyCode: string;
    /**
     * 如果启用双因素认证登录，则必填
     * @type {string}
     * @memberof EmailSignInRequest
     */
    twoFactorCode?: string | null;
}

/**
 * Check if a given object implements the EmailSignInRequest interface.
 */
export function instanceOfEmailSignInRequest(value: object): value is EmailSignInRequest {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('verifyCode' in value) || value['verifyCode'] === undefined) return false;
    return true;
}

export function EmailSignInRequestFromJSON(json: any): EmailSignInRequest {
    return EmailSignInRequestFromJSONTyped(json, false);
}

export function EmailSignInRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmailSignInRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'verifyCode': json['verifyCode'],
        'twoFactorCode': json['twoFactorCode'] == null ? undefined : json['twoFactorCode'],
    };
}

export function EmailSignInRequestToJSON(json: any): EmailSignInRequest {
    return EmailSignInRequestToJSONTyped(json, false);
}

export function EmailSignInRequestToJSONTyped(value?: EmailSignInRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'verifyCode': value['verifyCode'],
        'twoFactorCode': value['twoFactorCode'],
    };
}

