/* tslint:disable */
/* eslint-disable */
/**
 * 用户全部 API 文档
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EmailSignUpRequest
 */
export interface EmailSignUpRequest {
    /**
     * 用户邮箱地址
     * @type {string}
     * @memberof EmailSignUpRequest
     */
    email: string;
    /**
     * 用户密码，长度为6到32个字符
     * @type {string}
     * @memberof EmailSignUpRequest
     */
    pwd: string;
    /**
     * 邮箱验证码
     * @type {string}
     * @memberof EmailSignUpRequest
     */
    emailCode?: string | null;
    /**
     * 手机号，必须为11位数字
     * @type {string}
     * @memberof EmailSignUpRequest
     */
    phone?: string | null;
    /**
     * 手机验证码（只有启用的手机验证码功能时，才需要传入）
     * @type {string}
     * @memberof EmailSignUpRequest
     */
    phoneCode?: string | null;
    /**
     * 用户昵称
     * @type {string}
     * @memberof EmailSignUpRequest
     */
    nickName?: string | null;
    /**
     * 用户头像URL
     * @type {string}
     * @memberof EmailSignUpRequest
     */
    avatar?: string | null;
    /**
     * 自定义数据
     * @type {string}
     * @memberof EmailSignUpRequest
     */
    data?: string | null;
}

/**
 * Check if a given object implements the EmailSignUpRequest interface.
 */
export function instanceOfEmailSignUpRequest(value: object): value is EmailSignUpRequest {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('pwd' in value) || value['pwd'] === undefined) return false;
    return true;
}

export function EmailSignUpRequestFromJSON(json: any): EmailSignUpRequest {
    return EmailSignUpRequestFromJSONTyped(json, false);
}

export function EmailSignUpRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmailSignUpRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'pwd': json['pwd'],
        'emailCode': json['emailCode'] == null ? undefined : json['emailCode'],
        'phone': json['phone'] == null ? undefined : json['phone'],
        'phoneCode': json['phoneCode'] == null ? undefined : json['phoneCode'],
        'nickName': json['nickName'] == null ? undefined : json['nickName'],
        'avatar': json['avatar'] == null ? undefined : json['avatar'],
        'data': json['data'] == null ? undefined : json['data'],
    };
}

export function EmailSignUpRequestToJSON(json: any): EmailSignUpRequest {
    return EmailSignUpRequestToJSONTyped(json, false);
}

export function EmailSignUpRequestToJSONTyped(value?: EmailSignUpRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'pwd': value['pwd'],
        'emailCode': value['emailCode'],
        'phone': value['phone'],
        'phoneCode': value['phoneCode'],
        'nickName': value['nickName'],
        'avatar': value['avatar'],
        'data': value['data'],
    };
}

