/* tslint:disable */
/* eslint-disable */
/**
 * 全部  API 文档
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExecuteFunctionRequest
 */
export interface ExecuteFunctionRequest {
    /**
     * 函数标识
     * @type {string}
     * @memberof ExecuteFunctionRequest
     */
    functionKey?: string | null;
}

/**
 * Check if a given object implements the ExecuteFunctionRequest interface.
 */
export function instanceOfExecuteFunctionRequest(value: object): value is ExecuteFunctionRequest {
    return true;
}

export function ExecuteFunctionRequestFromJSON(json: any): ExecuteFunctionRequest {
    return ExecuteFunctionRequestFromJSONTyped(json, false);
}

export function ExecuteFunctionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExecuteFunctionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'functionKey': json['functionKey'] == null ? undefined : json['functionKey'],
    };
}

export function ExecuteFunctionRequestToJSON(json: any): ExecuteFunctionRequest {
    return ExecuteFunctionRequestToJSONTyped(json, false);
}

export function ExecuteFunctionRequestToJSONTyped(value?: ExecuteFunctionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'functionKey': value['functionKey'],
    };
}

