/* tslint:disable */
/* eslint-disable */
/**
 * 用户全部 API 文档
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExternalAccountPutRequest
 */
export interface ExternalAccountPutRequest {
    /**
     * 头像
     * @type {string}
     * @memberof ExternalAccountPutRequest
     */
    avatar?: string | null;
    /**
     * 自定义数据
     * @type {string}
     * @memberof ExternalAccountPutRequest
     */
    data?: string | null;
    /**
     * 启用
     * @type {boolean}
     * @memberof ExternalAccountPutRequest
     */
    enable?: boolean;
}

/**
 * Check if a given object implements the ExternalAccountPutRequest interface.
 */
export function instanceOfExternalAccountPutRequest(value: object): value is ExternalAccountPutRequest {
    return true;
}

export function ExternalAccountPutRequestFromJSON(json: any): ExternalAccountPutRequest {
    return ExternalAccountPutRequestFromJSONTyped(json, false);
}

export function ExternalAccountPutRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExternalAccountPutRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'avatar': json['avatar'] == null ? undefined : json['avatar'],
        'data': json['data'] == null ? undefined : json['data'],
        'enable': json['enable'] == null ? undefined : json['enable'],
    };
}

export function ExternalAccountPutRequestToJSON(json: any): ExternalAccountPutRequest {
    return ExternalAccountPutRequestToJSONTyped(json, false);
}

export function ExternalAccountPutRequestToJSONTyped(value?: ExternalAccountPutRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'avatar': value['avatar'],
        'data': value['data'],
        'enable': value['enable'],
    };
}

