/* tslint:disable */
/* eslint-disable */
/**
 * 用户全部 API 文档
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FileListResult } from './FileListResult';
import {
    FileListResultFromJSON,
    FileListResultFromJSONTyped,
    FileListResultToJSON,
    FileListResultToJSONTyped,
} from './FileListResult';

/**
 * 
 * @export
 * @interface FileListResultApiResponse
 */
export interface FileListResultApiResponse {
    /**
     * 状态码
     * @type {number}
     * @memberof FileListResultApiResponse
     */
    code?: number;
    /**
     * 
     * @type {FileListResult}
     * @memberof FileListResultApiResponse
     */
    data?: FileListResult;
    /**
     * 错误信息
     * @type {string}
     * @memberof FileListResultApiResponse
     */
    error?: string | null;
}

/**
 * Check if a given object implements the FileListResultApiResponse interface.
 */
export function instanceOfFileListResultApiResponse(value: object): value is FileListResultApiResponse {
    return true;
}

export function FileListResultApiResponseFromJSON(json: any): FileListResultApiResponse {
    return FileListResultApiResponseFromJSONTyped(json, false);
}

export function FileListResultApiResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): FileListResultApiResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'data': json['data'] == null ? undefined : FileListResultFromJSON(json['data']),
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function FileListResultApiResponseToJSON(json: any): FileListResultApiResponse {
    return FileListResultApiResponseToJSONTyped(json, false);
}

export function FileListResultApiResponseToJSONTyped(value?: FileListResultApiResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'data': FileListResultToJSON(value['data']),
        'error': value['error'],
    };
}

