/* tslint:disable */
/* eslint-disable */
/**
 * 用户全部 API 文档
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GetUserProfileResult } from './GetUserProfileResult';
import {
    GetUserProfileResultFromJSON,
    GetUserProfileResultFromJSONTyped,
    GetUserProfileResultToJSON,
    GetUserProfileResultToJSONTyped,
} from './GetUserProfileResult';

/**
 * 
 * @export
 * @interface GetUserProfileResultApiResponse
 */
export interface GetUserProfileResultApiResponse {
    /**
     * 状态码
     * @type {number}
     * @memberof GetUserProfileResultApiResponse
     */
    code?: number;
    /**
     * 
     * @type {GetUserProfileResult}
     * @memberof GetUserProfileResultApiResponse
     */
    data?: GetUserProfileResult;
    /**
     * 错误信息
     * @type {string}
     * @memberof GetUserProfileResultApiResponse
     */
    error?: string | null;
}

/**
 * Check if a given object implements the GetUserProfileResultApiResponse interface.
 */
export function instanceOfGetUserProfileResultApiResponse(value: object): value is GetUserProfileResultApiResponse {
    return true;
}

export function GetUserProfileResultApiResponseFromJSON(json: any): GetUserProfileResultApiResponse {
    return GetUserProfileResultApiResponseFromJSONTyped(json, false);
}

export function GetUserProfileResultApiResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetUserProfileResultApiResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'data': json['data'] == null ? undefined : GetUserProfileResultFromJSON(json['data']),
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function GetUserProfileResultApiResponseToJSON(json: any): GetUserProfileResultApiResponse {
    return GetUserProfileResultApiResponseToJSONTyped(json, false);
}

export function GetUserProfileResultApiResponseToJSONTyped(value?: GetUserProfileResultApiResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'data': GetUserProfileResultToJSON(value['data']),
        'error': value['error'],
    };
}

