/* tslint:disable */
/* eslint-disable */
/**
 * 用户全部 API 文档
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GrantResult
 */
export interface GrantResult {
    /**
     * 
     * @type {number}
     * @memberof GrantResult
     */
    code?: number;
    /**
     * 
     * @type {string}
     * @memberof GrantResult
     */
    error?: string | null;
    /**
     * 
     * @type {number}
     * @memberof GrantResult
     */
    expiresIn?: number;
    /**
     * 
     * @type {string}
     * @memberof GrantResult
     */
    data?: string | null;
}

/**
 * Check if a given object implements the GrantResult interface.
 */
export function instanceOfGrantResult(value: object): value is GrantResult {
    return true;
}

export function GrantResultFromJSON(json: any): GrantResult {
    return GrantResultFromJSONTyped(json, false);
}

export function GrantResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): GrantResult {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'error': json['error'] == null ? undefined : json['error'],
        'expiresIn': json['expires_in'] == null ? undefined : json['expires_in'],
        'data': json['data'] == null ? undefined : json['data'],
    };
}

export function GrantResultToJSON(json: any): GrantResult {
    return GrantResultToJSONTyped(json, false);
}

export function GrantResultToJSONTyped(value?: GrantResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'error': value['error'],
        'expires_in': value['expiresIn'],
        'data': value['data'],
    };
}

