/* tslint:disable */
/* eslint-disable */
/**
 * 用户全部 API 文档
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GrantRequest
 */
export interface GrantRequest {
    /**
     * 返回地址。默认无限制，也可在【安全-开放认证网址白名单】配置
     * @type {string}
     * @memberof GrantRequest
     */
    redirectUri?: string | null;
    /**
     * 授权类型。可选：email、phone、unionid、account
     * @type {string}
     * @memberof GrantRequest
     */
    grantType: string;
    /**
     * 自定义授权范围，用英文空格分隔
     * @type {string}
     * @memberof GrantRequest
     */
    scopes: string;
    /**
     * 用户名。授权类型为：email/phone/account必填
     * @type {string}
     * @memberof GrantRequest
     */
    userName?: string | null;
    /**
     * 登录密码。授权类型为：email/phone/account必填
     * @type {string}
     * @memberof GrantRequest
     */
    password?: string | null;
    /**
     * unionId。授权类型为：unionid必填
     * @type {string}
     * @memberof GrantRequest
     */
    unionId?: string | null;
    /**
     * 平台。授权类型为：unionid必填
     * @type {string}
     * @memberof GrantRequest
     */
    platform?: string | null;
    /**
     * 授权有效期。1~99天
     * @type {number}
     * @memberof GrantRequest
     */
    expireInDays?: number;
}

/**
 * Check if a given object implements the GrantRequest interface.
 */
export function instanceOfGrantRequest(value: object): value is GrantRequest {
    if (!('grantType' in value) || value['grantType'] === undefined) return false;
    if (!('scopes' in value) || value['scopes'] === undefined) return false;
    return true;
}

export function GrantRequestFromJSON(json: any): GrantRequest {
    return GrantRequestFromJSONTyped(json, false);
}

export function GrantRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GrantRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'redirectUri': json['redirect_uri'] == null ? undefined : json['redirect_uri'],
        'grantType': json['grant_type'],
        'scopes': json['scopes'],
        'userName': json['userName'] == null ? undefined : json['userName'],
        'password': json['password'] == null ? undefined : json['password'],
        'unionId': json['unionId'] == null ? undefined : json['unionId'],
        'platform': json['platform'] == null ? undefined : json['platform'],
        'expireInDays': json['expireInDays'] == null ? undefined : json['expireInDays'],
    };
}

export function GrantRequestToJSON(json: any): GrantRequest {
    return GrantRequestToJSONTyped(json, false);
}

export function GrantRequestToJSONTyped(value?: GrantRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'redirect_uri': value['redirectUri'],
        'grant_type': value['grantType'],
        'scopes': value['scopes'],
        'userName': value['userName'],
        'password': value['password'],
        'unionId': value['unionId'],
        'platform': value['platform'],
        'expireInDays': value['expireInDays'],
    };
}

