/* tslint:disable */
/* eslint-disable */
/**
 * 全部  API 文档
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ListResponseItem } from './ListResponseItem';
import {
    ListResponseItemFromJSON,
    ListResponseItemFromJSONTyped,
    ListResponseItemToJSON,
    ListResponseItemToJSONTyped,
} from './ListResponseItem';

/**
 * 
 * @export
 * @interface ListResponseItemListApiResponse
 */
export interface ListResponseItemListApiResponse {
    /**
     * 状态码
     * @type {number}
     * @memberof ListResponseItemListApiResponse
     */
    code?: number;
    /**
     * 响应数据
     * @type {Array<ListResponseItem>}
     * @memberof ListResponseItemListApiResponse
     */
    data?: Array<ListResponseItem> | null;
    /**
     * 错误信息
     * @type {string}
     * @memberof ListResponseItemListApiResponse
     */
    error?: string | null;
}

/**
 * Check if a given object implements the ListResponseItemListApiResponse interface.
 */
export function instanceOfListResponseItemListApiResponse(value: object): value is ListResponseItemListApiResponse {
    return true;
}

export function ListResponseItemListApiResponseFromJSON(json: any): ListResponseItemListApiResponse {
    return ListResponseItemListApiResponseFromJSONTyped(json, false);
}

export function ListResponseItemListApiResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListResponseItemListApiResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(ListResponseItemFromJSON)),
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function ListResponseItemListApiResponseToJSON(json: any): ListResponseItemListApiResponse {
    return ListResponseItemListApiResponseToJSONTyped(json, false);
}

export function ListResponseItemListApiResponseToJSONTyped(value?: ListResponseItemListApiResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(ListResponseItemToJSON)),
        'error': value['error'],
    };
}

