/* tslint:disable */
/* eslint-disable */
/**
 * 全部  API 文档
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OAuthAccountSignInRequest
 */
export interface OAuthAccountSignInRequest {
    /**
     * UnionID，长度必须在1到50个字符之间，只能包含字母、数字、下划线和连字符
     * @type {string}
     * @memberof OAuthAccountSignInRequest
     */
    unionID: string;
    /**
     * 平台，长度必须在1到20个字符之间，只能包含字母和数字
     * @type {string}
     * @memberof OAuthAccountSignInRequest
     */
    platform: string;
    /**
     * 双因素认证代码，如果启用双因素认证登录，则必填，长度必须为6个字符，只能包含数字
     * @type {string}
     * @memberof OAuthAccountSignInRequest
     */
    twoFactorCode?: string | null;
}

/**
 * Check if a given object implements the OAuthAccountSignInRequest interface.
 */
export function instanceOfOAuthAccountSignInRequest(value: object): value is OAuthAccountSignInRequest {
    if (!('unionID' in value) || value['unionID'] === undefined) return false;
    if (!('platform' in value) || value['platform'] === undefined) return false;
    return true;
}

export function OAuthAccountSignInRequestFromJSON(json: any): OAuthAccountSignInRequest {
    return OAuthAccountSignInRequestFromJSONTyped(json, false);
}

export function OAuthAccountSignInRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): OAuthAccountSignInRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'unionID': json['unionID'],
        'platform': json['platform'],
        'twoFactorCode': json['twoFactorCode'] == null ? undefined : json['twoFactorCode'],
    };
}

export function OAuthAccountSignInRequestToJSON(json: any): OAuthAccountSignInRequest {
    return OAuthAccountSignInRequestToJSONTyped(json, false);
}

export function OAuthAccountSignInRequestToJSONTyped(value?: OAuthAccountSignInRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'unionID': value['unionID'],
        'platform': value['platform'],
        'twoFactorCode': value['twoFactorCode'],
    };
}

