/* tslint:disable */
/* eslint-disable */
/**
 * 全部  API 文档
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OAuthAccountBindRequest
 */
export interface OAuthAccountBindRequest {
    /**
     * 
     * @type {string}
     * @memberof OAuthAccountBindRequest
     */
    unionID: string;
    /**
     * 
     * @type {string}
     * @memberof OAuthAccountBindRequest
     */
    platform: string;
    /**
     * 
     * @type {string}
     * @memberof OAuthAccountBindRequest
     */
    platformName: string;
    /**
     * 
     * @type {string}
     * @memberof OAuthAccountBindRequest
     */
    avatar?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OAuthAccountBindRequest
     */
    data?: string | null;
}

/**
 * Check if a given object implements the OAuthAccountBindRequest interface.
 */
export function instanceOfOAuthAccountBindRequest(value: object): value is OAuthAccountBindRequest {
    if (!('unionID' in value) || value['unionID'] === undefined) return false;
    if (!('platform' in value) || value['platform'] === undefined) return false;
    if (!('platformName' in value) || value['platformName'] === undefined) return false;
    return true;
}

export function OAuthAccountBindRequestFromJSON(json: any): OAuthAccountBindRequest {
    return OAuthAccountBindRequestFromJSONTyped(json, false);
}

export function OAuthAccountBindRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): OAuthAccountBindRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'unionID': json['unionID'],
        'platform': json['platform'],
        'platformName': json['platformName'],
        'avatar': json['avatar'] == null ? undefined : json['avatar'],
        'data': json['data'] == null ? undefined : json['data'],
    };
}

export function OAuthAccountBindRequestToJSON(json: any): OAuthAccountBindRequest {
    return OAuthAccountBindRequestToJSONTyped(json, false);
}

export function OAuthAccountBindRequestToJSONTyped(value?: OAuthAccountBindRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'unionID': value['unionID'],
        'platform': value['platform'],
        'platformName': value['platformName'],
        'avatar': value['avatar'],
        'data': value['data'],
    };
}

