/* tslint:disable */
/* eslint-disable */
/**
 * 用户全部 API 文档
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ObjectListApiResponse
 */
export interface ObjectListApiResponse {
    /**
     * 状态码
     * @type {number}
     * @memberof ObjectListApiResponse
     */
    code?: number;
    /**
     * 响应数据
     * @type {Array<any>}
     * @memberof ObjectListApiResponse
     */
    data?: Array<any> | null;
    /**
     * 错误信息
     * @type {string}
     * @memberof ObjectListApiResponse
     */
    error?: string | null;
}

/**
 * Check if a given object implements the ObjectListApiResponse interface.
 */
export function instanceOfObjectListApiResponse(value: object): value is ObjectListApiResponse {
    return true;
}

export function ObjectListApiResponseFromJSON(json: any): ObjectListApiResponse {
    return ObjectListApiResponseFromJSONTyped(json, false);
}

export function ObjectListApiResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ObjectListApiResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'data': json['data'] == null ? undefined : json['data'],
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function ObjectListApiResponseToJSON(json: any): ObjectListApiResponse {
    return ObjectListApiResponseToJSONTyped(json, false);
}

export function ObjectListApiResponseToJSONTyped(value?: ObjectListApiResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'data': value['data'],
        'error': value['error'],
    };
}

