/* tslint:disable */
/* eslint-disable */
/**
 * 用户全部 API 文档
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Order } from './Order';
import {
    OrderFromJSON,
    OrderFromJSONTyped,
    OrderToJSON,
    OrderToJSONTyped,
} from './Order';

/**
 * 
 * @export
 * @interface OrderApiResponse
 */
export interface OrderApiResponse {
    /**
     * 状态码
     * @type {number}
     * @memberof OrderApiResponse
     */
    code?: number;
    /**
     * 
     * @type {Order}
     * @memberof OrderApiResponse
     */
    data?: Order;
    /**
     * 错误信息
     * @type {string}
     * @memberof OrderApiResponse
     */
    error?: string | null;
}

/**
 * Check if a given object implements the OrderApiResponse interface.
 */
export function instanceOfOrderApiResponse(value: object): value is OrderApiResponse {
    return true;
}

export function OrderApiResponseFromJSON(json: any): OrderApiResponse {
    return OrderApiResponseFromJSONTyped(json, false);
}

export function OrderApiResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderApiResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'data': json['data'] == null ? undefined : OrderFromJSON(json['data']),
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function OrderApiResponseToJSON(json: any): OrderApiResponse {
    return OrderApiResponseToJSONTyped(json, false);
}

export function OrderApiResponseToJSONTyped(value?: OrderApiResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'data': OrderToJSON(value['data']),
        'error': value['error'],
    };
}

