/* tslint:disable */
/* eslint-disable */
/**
 * 用户全部 API 文档
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Order } from './Order';
import {
    OrderFromJSON,
    OrderFromJSONTyped,
    OrderToJSON,
    OrderToJSONTyped,
} from './Order';

/**
 * 
 * @export
 * @interface OrderListResult
 */
export interface OrderListResult {
    /**
     * 
     * @type {number}
     * @memberof OrderListResult
     */
    total?: number;
    /**
     * 
     * @type {Array<Order>}
     * @memberof OrderListResult
     */
    data?: Array<Order> | null;
}

/**
 * Check if a given object implements the OrderListResult interface.
 */
export function instanceOfOrderListResult(value: object): value is OrderListResult {
    return true;
}

export function OrderListResultFromJSON(json: any): OrderListResult {
    return OrderListResultFromJSONTyped(json, false);
}

export function OrderListResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderListResult {
    if (json == null) {
        return json;
    }
    return {
        
        'total': json['total'] == null ? undefined : json['total'],
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(OrderFromJSON)),
    };
}

export function OrderListResultToJSON(json: any): OrderListResult {
    return OrderListResultToJSONTyped(json, false);
}

export function OrderListResultToJSONTyped(value?: OrderListResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total': value['total'],
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(OrderToJSON)),
    };
}

