/* tslint:disable */
/* eslint-disable */
/**
 * 全部  API 文档
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PhoneSignInRequest
 */
export interface PhoneSignInRequest {
    /**
     * 
     * @type {string}
     * @memberof PhoneSignInRequest
     */
    phone: string;
    /**
     * 
     * @type {string}
     * @memberof PhoneSignInRequest
     */
    verifyCode: string;
    /**
     * 如果启用双因素认证登录，则必填
     * @type {string}
     * @memberof PhoneSignInRequest
     */
    twoFactorCode?: string | null;
}

/**
 * Check if a given object implements the PhoneSignInRequest interface.
 */
export function instanceOfPhoneSignInRequest(value: object): value is PhoneSignInRequest {
    if (!('phone' in value) || value['phone'] === undefined) return false;
    if (!('verifyCode' in value) || value['verifyCode'] === undefined) return false;
    return true;
}

export function PhoneSignInRequestFromJSON(json: any): PhoneSignInRequest {
    return PhoneSignInRequestFromJSONTyped(json, false);
}

export function PhoneSignInRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PhoneSignInRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'phone': json['phone'],
        'verifyCode': json['verifyCode'],
        'twoFactorCode': json['twoFactorCode'] == null ? undefined : json['twoFactorCode'],
    };
}

export function PhoneSignInRequestToJSON(json: any): PhoneSignInRequest {
    return PhoneSignInRequestToJSONTyped(json, false);
}

export function PhoneSignInRequestToJSONTyped(value?: PhoneSignInRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'phone': value['phone'],
        'verifyCode': value['verifyCode'],
        'twoFactorCode': value['twoFactorCode'],
    };
}

