/* tslint:disable */
/* eslint-disable */
/**
 * 用户全部 API 文档
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface QRCodeSignInRequest
 */
export interface QRCodeSignInRequest {
    /**
     * 登录密钥
     * @type {number}
     * @memberof QRCodeSignInRequest
     */
    signInKey: number;
}

/**
 * Check if a given object implements the QRCodeSignInRequest interface.
 */
export function instanceOfQRCodeSignInRequest(value: object): value is QRCodeSignInRequest {
    if (!('signInKey' in value) || value['signInKey'] === undefined) return false;
    return true;
}

export function QRCodeSignInRequestFromJSON(json: any): QRCodeSignInRequest {
    return QRCodeSignInRequestFromJSONTyped(json, false);
}

export function QRCodeSignInRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): QRCodeSignInRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'signInKey': json['signInKey'],
    };
}

export function QRCodeSignInRequestToJSON(json: any): QRCodeSignInRequest {
    return QRCodeSignInRequestToJSONTyped(json, false);
}

export function QRCodeSignInRequestToJSONTyped(value?: QRCodeSignInRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'signInKey': value['signInKey'],
    };
}

