/* tslint:disable */
/* eslint-disable */
/**
 * 用户全部 API 文档
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 支付宝返回页面通知请求
 * @export
 * @interface ReturnPageNotifyRequest
 */
export interface ReturnPageNotifyRequest {
    /**
     * 应用ID
     * @type {string}
     * @memberof ReturnPageNotifyRequest
     */
    appId?: string | null;
    /**
     * 授权应用ID
     * @type {string}
     * @memberof ReturnPageNotifyRequest
     */
    authAppId?: string | null;
    /**
     * 字符集
     * @type {string}
     * @memberof ReturnPageNotifyRequest
     */
    charset?: string | null;
    /**
     * 接口名称
     * @type {string}
     * @memberof ReturnPageNotifyRequest
     */
    method?: string | null;
    /**
     * 商户订单号
     * @type {string}
     * @memberof ReturnPageNotifyRequest
     */
    outTradeNo?: string | null;
    /**
     * 卖家支付宝用户号
     * @type {string}
     * @memberof ReturnPageNotifyRequest
     */
    sellerId?: string | null;
    /**
     * 签名
     * @type {string}
     * @memberof ReturnPageNotifyRequest
     */
    sign?: string | null;
    /**
     * 签名类型
     * @type {string}
     * @memberof ReturnPageNotifyRequest
     */
    signType?: string | null;
    /**
     * 时间戳
     * @type {string}
     * @memberof ReturnPageNotifyRequest
     */
    timestamp?: string | null;
    /**
     * 订单总金额
     * @type {string}
     * @memberof ReturnPageNotifyRequest
     */
    totalAmount?: string | null;
    /**
     * 支付宝交易号
     * @type {string}
     * @memberof ReturnPageNotifyRequest
     */
    tradeNo?: string | null;
    /**
     * 接口版本
     * @type {string}
     * @memberof ReturnPageNotifyRequest
     */
    version?: string | null;
}

/**
 * Check if a given object implements the ReturnPageNotifyRequest interface.
 */
export function instanceOfReturnPageNotifyRequest(value: object): value is ReturnPageNotifyRequest {
    return true;
}

export function ReturnPageNotifyRequestFromJSON(json: any): ReturnPageNotifyRequest {
    return ReturnPageNotifyRequestFromJSONTyped(json, false);
}

export function ReturnPageNotifyRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReturnPageNotifyRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'appId': json['app_id'] == null ? undefined : json['app_id'],
        'authAppId': json['auth_app_id'] == null ? undefined : json['auth_app_id'],
        'charset': json['charset'] == null ? undefined : json['charset'],
        'method': json['method'] == null ? undefined : json['method'],
        'outTradeNo': json['out_trade_no'] == null ? undefined : json['out_trade_no'],
        'sellerId': json['seller_id'] == null ? undefined : json['seller_id'],
        'sign': json['sign'] == null ? undefined : json['sign'],
        'signType': json['sign_type'] == null ? undefined : json['sign_type'],
        'timestamp': json['timestamp'] == null ? undefined : json['timestamp'],
        'totalAmount': json['total_amount'] == null ? undefined : json['total_amount'],
        'tradeNo': json['trade_no'] == null ? undefined : json['trade_no'],
        'version': json['version'] == null ? undefined : json['version'],
    };
}

export function ReturnPageNotifyRequestToJSON(json: any): ReturnPageNotifyRequest {
    return ReturnPageNotifyRequestToJSONTyped(json, false);
}

export function ReturnPageNotifyRequestToJSONTyped(value?: ReturnPageNotifyRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'app_id': value['appId'],
        'auth_app_id': value['authAppId'],
        'charset': value['charset'],
        'method': value['method'],
        'out_trade_no': value['outTradeNo'],
        'seller_id': value['sellerId'],
        'sign': value['sign'],
        'sign_type': value['signType'],
        'timestamp': value['timestamp'],
        'total_amount': value['totalAmount'],
        'trade_no': value['tradeNo'],
        'version': value['version'],
    };
}

