/* tslint:disable */
/* eslint-disable */
/**
 * 全部  API 文档
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ServiceSettingProviderPostResult
 */
export interface ServiceSettingProviderPostResult {
    /**
     * 
     * @type {number}
     * @memberof ServiceSettingProviderPostResult
     */
    id?: number;
}

/**
 * Check if a given object implements the ServiceSettingProviderPostResult interface.
 */
export function instanceOfServiceSettingProviderPostResult(value: object): value is ServiceSettingProviderPostResult {
    return true;
}

export function ServiceSettingProviderPostResultFromJSON(json: any): ServiceSettingProviderPostResult {
    return ServiceSettingProviderPostResultFromJSONTyped(json, false);
}

export function ServiceSettingProviderPostResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServiceSettingProviderPostResult {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function ServiceSettingProviderPostResultToJSON(json: any): ServiceSettingProviderPostResult {
    return ServiceSettingProviderPostResultToJSONTyped(json, false);
}

export function ServiceSettingProviderPostResultToJSONTyped(value?: ServiceSettingProviderPostResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
    };
}

