/* tslint:disable */
/* eslint-disable */
/**
 * 全部  API 文档
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ServiceGroup } from './ServiceGroup';
import {
    ServiceGroupFromJSON,
    ServiceGroupFromJSONTyped,
    ServiceGroupToJSON,
    ServiceGroupToJSONTyped,
} from './ServiceGroup';

/**
 * 
 * @export
 * @interface ServiceGroupApiResponse
 */
export interface ServiceGroupApiResponse {
    /**
     * 状态码
     * @type {number}
     * @memberof ServiceGroupApiResponse
     */
    code?: number;
    /**
     * 
     * @type {ServiceGroup}
     * @memberof ServiceGroupApiResponse
     */
    data?: ServiceGroup;
    /**
     * 错误信息
     * @type {string}
     * @memberof ServiceGroupApiResponse
     */
    error?: string | null;
}

/**
 * Check if a given object implements the ServiceGroupApiResponse interface.
 */
export function instanceOfServiceGroupApiResponse(value: object): value is ServiceGroupApiResponse {
    return true;
}

export function ServiceGroupApiResponseFromJSON(json: any): ServiceGroupApiResponse {
    return ServiceGroupApiResponseFromJSONTyped(json, false);
}

export function ServiceGroupApiResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServiceGroupApiResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'data': json['data'] == null ? undefined : ServiceGroupFromJSON(json['data']),
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function ServiceGroupApiResponseToJSON(json: any): ServiceGroupApiResponse {
    return ServiceGroupApiResponseToJSONTyped(json, false);
}

export function ServiceGroupApiResponseToJSONTyped(value?: ServiceGroupApiResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'data': ServiceGroupToJSON(value['data']),
        'error': value['error'],
    };
}

