/* tslint:disable */
/* eslint-disable */
/**
 * 全部  API 文档
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ServiceSettingSettingPostResult } from './ServiceSettingSettingPostResult';
import {
    ServiceSettingSettingPostResultFromJSON,
    ServiceSettingSettingPostResultFromJSONTyped,
    ServiceSettingSettingPostResultToJSON,
    ServiceSettingSettingPostResultToJSONTyped,
} from './ServiceSettingSettingPostResult';

/**
 * 
 * @export
 * @interface ServiceSettingSettingPostResultApiResponse
 */
export interface ServiceSettingSettingPostResultApiResponse {
    /**
     * 状态码
     * @type {number}
     * @memberof ServiceSettingSettingPostResultApiResponse
     */
    code?: number;
    /**
     * 
     * @type {ServiceSettingSettingPostResult}
     * @memberof ServiceSettingSettingPostResultApiResponse
     */
    data?: ServiceSettingSettingPostResult;
    /**
     * 错误信息
     * @type {string}
     * @memberof ServiceSettingSettingPostResultApiResponse
     */
    error?: string | null;
}

/**
 * Check if a given object implements the ServiceSettingSettingPostResultApiResponse interface.
 */
export function instanceOfServiceSettingSettingPostResultApiResponse(value: object): value is ServiceSettingSettingPostResultApiResponse {
    return true;
}

export function ServiceSettingSettingPostResultApiResponseFromJSON(json: any): ServiceSettingSettingPostResultApiResponse {
    return ServiceSettingSettingPostResultApiResponseFromJSONTyped(json, false);
}

export function ServiceSettingSettingPostResultApiResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServiceSettingSettingPostResultApiResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'data': json['data'] == null ? undefined : ServiceSettingSettingPostResultFromJSON(json['data']),
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function ServiceSettingSettingPostResultApiResponseToJSON(json: any): ServiceSettingSettingPostResultApiResponse {
    return ServiceSettingSettingPostResultApiResponseToJSONTyped(json, false);
}

export function ServiceSettingSettingPostResultApiResponseToJSONTyped(value?: ServiceSettingSettingPostResultApiResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'data': ServiceSettingSettingPostResultToJSON(value['data']),
        'error': value['error'],
    };
}

