/* tslint:disable */
/* eslint-disable */
/**
 * 全部  API 文档
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ServiceItem } from './ServiceItem';
import {
    ServiceItemFromJSON,
    ServiceItemFromJSONTyped,
    ServiceItemToJSON,
    ServiceItemToJSONTyped,
} from './ServiceItem';

/**
 * 
 * @export
 * @interface ServiceItemApiResponse
 */
export interface ServiceItemApiResponse {
    /**
     * 状态码
     * @type {number}
     * @memberof ServiceItemApiResponse
     */
    code?: number;
    /**
     * 
     * @type {ServiceItem}
     * @memberof ServiceItemApiResponse
     */
    data?: ServiceItem;
    /**
     * 错误信息
     * @type {string}
     * @memberof ServiceItemApiResponse
     */
    error?: string | null;
}

/**
 * Check if a given object implements the ServiceItemApiResponse interface.
 */
export function instanceOfServiceItemApiResponse(value: object): value is ServiceItemApiResponse {
    return true;
}

export function ServiceItemApiResponseFromJSON(json: any): ServiceItemApiResponse {
    return ServiceItemApiResponseFromJSONTyped(json, false);
}

export function ServiceItemApiResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServiceItemApiResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'data': json['data'] == null ? undefined : ServiceItemFromJSON(json['data']),
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function ServiceItemApiResponseToJSON(json: any): ServiceItemApiResponse {
    return ServiceItemApiResponseToJSONTyped(json, false);
}

export function ServiceItemApiResponseToJSONTyped(value?: ServiceItemApiResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'data': ServiceItemToJSON(value['data']),
        'error': value['error'],
    };
}

