/* tslint:disable */
/* eslint-disable */
/**
 * 用户全部 API 文档
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SetupCode } from './SetupCode';
import {
    SetupCodeFromJSON,
    SetupCodeFromJSONTyped,
    SetupCodeToJSON,
    SetupCodeToJSONTyped,
} from './SetupCode';

/**
 * 
 * @export
 * @interface SetupCodeApiResponse
 */
export interface SetupCodeApiResponse {
    /**
     * 状态码
     * @type {number}
     * @memberof SetupCodeApiResponse
     */
    code?: number;
    /**
     * 
     * @type {SetupCode}
     * @memberof SetupCodeApiResponse
     */
    data?: SetupCode;
    /**
     * 错误信息
     * @type {string}
     * @memberof SetupCodeApiResponse
     */
    error?: string | null;
}

/**
 * Check if a given object implements the SetupCodeApiResponse interface.
 */
export function instanceOfSetupCodeApiResponse(value: object): value is SetupCodeApiResponse {
    return true;
}

export function SetupCodeApiResponseFromJSON(json: any): SetupCodeApiResponse {
    return SetupCodeApiResponseFromJSONTyped(json, false);
}

export function SetupCodeApiResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetupCodeApiResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'data': json['data'] == null ? undefined : SetupCodeFromJSON(json['data']),
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function SetupCodeApiResponseToJSON(json: any): SetupCodeApiResponse {
    return SetupCodeApiResponseToJSONTyped(json, false);
}

export function SetupCodeApiResponseToJSONTyped(value?: SetupCodeApiResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'data': SetupCodeToJSON(value['data']),
        'error': value['error'],
    };
}

