/* tslint:disable */
/* eslint-disable */
/**
 * 用户全部 API 文档
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SignInRequest
 */
export interface SignInRequest {
    /**
     * 用户名，长度必须在6到32个字符之间，只能包含字母、数字、下划线和连字符
     * @type {string}
     * @memberof SignInRequest
     */
    userName: string;
    /**
     * 用户密码，长度必须在6到50个字符之间，可以包含数字、大小写字母、下划线、连字符和特殊符号
     * @type {string}
     * @memberof SignInRequest
     */
    pwd: string;
    /**
     * 双因素认证代码，如果启用双因素认证登录，则必填，长度必须为6个字符，只能包含数字
     * @type {string}
     * @memberof SignInRequest
     */
    twoFactorCode?: string | null;
}

/**
 * Check if a given object implements the SignInRequest interface.
 */
export function instanceOfSignInRequest(value: object): value is SignInRequest {
    if (!('userName' in value) || value['userName'] === undefined) return false;
    if (!('pwd' in value) || value['pwd'] === undefined) return false;
    return true;
}

export function SignInRequestFromJSON(json: any): SignInRequest {
    return SignInRequestFromJSONTyped(json, false);
}

export function SignInRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SignInRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'userName': json['userName'],
        'pwd': json['pwd'],
        'twoFactorCode': json['twoFactorCode'] == null ? undefined : json['twoFactorCode'],
    };
}

export function SignInRequestToJSON(json: any): SignInRequest {
    return SignInRequestToJSONTyped(json, false);
}

export function SignInRequestToJSONTyped(value?: SignInRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userName': value['userName'],
        'pwd': value['pwd'],
        'twoFactorCode': value['twoFactorCode'],
    };
}

