/* tslint:disable */
/* eslint-disable */
/**
 * 全部  API 文档
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SystemFileItem
 */
export interface SystemFileItem {
    /**
     * 
     * @type {string}
     * @memberof SystemFileItem
     */
    name?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof SystemFileItem
     */
    createDate?: Date;
    /**
     * 
     * @type {Date}
     * @memberof SystemFileItem
     */
    lastUpdate?: Date;
    /**
     * 
     * @type {number}
     * @memberof SystemFileItem
     */
    fileSize?: number | null;
}

/**
 * Check if a given object implements the SystemFileItem interface.
 */
export function instanceOfSystemFileItem(value: object): value is SystemFileItem {
    return true;
}

export function SystemFileItemFromJSON(json: any): SystemFileItem {
    return SystemFileItemFromJSONTyped(json, false);
}

export function SystemFileItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): SystemFileItem {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'createDate': json['createDate'] == null ? undefined : (new Date(json['createDate'])),
        'lastUpdate': json['lastUpdate'] == null ? undefined : (new Date(json['lastUpdate'])),
        'fileSize': json['fileSize'] == null ? undefined : json['fileSize'],
    };
}

export function SystemFileItemToJSON(json: any): SystemFileItem {
    return SystemFileItemToJSONTyped(json, false);
}

export function SystemFileItemToJSONTyped(value?: SystemFileItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'createDate': value['createDate'] == null ? undefined : ((value['createDate']).toISOString()),
        'lastUpdate': value['lastUpdate'] == null ? undefined : ((value['lastUpdate']).toISOString()),
        'fileSize': value['fileSize'],
    };
}

