/* tslint:disable */
/* eslint-disable */
/**
 * 用户全部 API 文档
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TapPayInfo
 */
export interface TapPayInfo {
    /**
     * 
     * @type {string}
     * @memberof TapPayInfo
     */
    paymentMediumType?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TapPayInfo
     */
    totalDiscountAmount?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TapPayInfo
     */
    totalDiscountName?: string | null;
}

/**
 * Check if a given object implements the TapPayInfo interface.
 */
export function instanceOfTapPayInfo(value: object): value is TapPayInfo {
    return true;
}

export function TapPayInfoFromJSON(json: any): TapPayInfo {
    return TapPayInfoFromJSONTyped(json, false);
}

export function TapPayInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TapPayInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'paymentMediumType': json['paymentMediumType'] == null ? undefined : json['paymentMediumType'],
        'totalDiscountAmount': json['totalDiscountAmount'] == null ? undefined : json['totalDiscountAmount'],
        'totalDiscountName': json['totalDiscountName'] == null ? undefined : json['totalDiscountName'],
    };
}

export function TapPayInfoToJSON(json: any): TapPayInfo {
    return TapPayInfoToJSONTyped(json, false);
}

export function TapPayInfoToJSONTyped(value?: TapPayInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'paymentMediumType': value['paymentMediumType'],
        'totalDiscountAmount': value['totalDiscountAmount'],
        'totalDiscountName': value['totalDiscountName'],
    };
}

