/* tslint:disable */
/* eslint-disable */
/**
 * 用户全部 API 文档
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TokenModel } from './TokenModel';
import {
    TokenModelFromJSON,
    TokenModelFromJSONTyped,
    TokenModelToJSON,
    TokenModelToJSONTyped,
} from './TokenModel';

/**
 * 
 * @export
 * @interface TokenModelApiResponse
 */
export interface TokenModelApiResponse {
    /**
     * 状态码
     * @type {number}
     * @memberof TokenModelApiResponse
     */
    code?: number;
    /**
     * 
     * @type {TokenModel}
     * @memberof TokenModelApiResponse
     */
    data?: TokenModel;
    /**
     * 错误信息
     * @type {string}
     * @memberof TokenModelApiResponse
     */
    error?: string | null;
}

/**
 * Check if a given object implements the TokenModelApiResponse interface.
 */
export function instanceOfTokenModelApiResponse(value: object): value is TokenModelApiResponse {
    return true;
}

export function TokenModelApiResponseFromJSON(json: any): TokenModelApiResponse {
    return TokenModelApiResponseFromJSONTyped(json, false);
}

export function TokenModelApiResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TokenModelApiResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'data': json['data'] == null ? undefined : TokenModelFromJSON(json['data']),
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function TokenModelApiResponseToJSON(json: any): TokenModelApiResponse {
    return TokenModelApiResponseToJSONTyped(json, false);
}

export function TokenModelApiResponseToJSONTyped(value?: TokenModelApiResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'data': TokenModelToJSON(value['data']),
        'error': value['error'],
    };
}

