/* tslint:disable */
/* eslint-disable */
/**
 * 用户全部 API 文档
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TradeFundBill
 */
export interface TradeFundBill {
    /**
     * 
     * @type {string}
     * @memberof TradeFundBill
     */
    amount?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TradeFundBill
     */
    bankCode?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TradeFundBill
     */
    fundChannel?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TradeFundBill
     */
    fundType?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TradeFundBill
     */
    realAmount?: string | null;
}

/**
 * Check if a given object implements the TradeFundBill interface.
 */
export function instanceOfTradeFundBill(value: object): value is TradeFundBill {
    return true;
}

export function TradeFundBillFromJSON(json: any): TradeFundBill {
    return TradeFundBillFromJSONTyped(json, false);
}

export function TradeFundBillFromJSONTyped(json: any, ignoreDiscriminator: boolean): TradeFundBill {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'] == null ? undefined : json['amount'],
        'bankCode': json['bankCode'] == null ? undefined : json['bankCode'],
        'fundChannel': json['fundChannel'] == null ? undefined : json['fundChannel'],
        'fundType': json['fundType'] == null ? undefined : json['fundType'],
        'realAmount': json['realAmount'] == null ? undefined : json['realAmount'],
    };
}

export function TradeFundBillToJSON(json: any): TradeFundBill {
    return TradeFundBillToJSONTyped(json, false);
}

export function TradeFundBillToJSONTyped(value?: TradeFundBill | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount': value['amount'],
        'bankCode': value['bankCode'],
        'fundChannel': value['fundChannel'],
        'fundType': value['fundType'],
        'realAmount': value['realAmount'],
    };
}

