/* tslint:disable */
/* eslint-disable */
/**
 * 用户全部 API 文档
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateProfileRequest
 */
export interface UpdateProfileRequest {
    /**
     * 用户头像的链接或路径，长度不能超过255个字符
     * @type {string}
     * @memberof UpdateProfileRequest
     */
    avatar?: string | null;
    /**
     * 用户的其他数据，可以是序列化后的对象或JSON字符串
     * @type {string}
     * @memberof UpdateProfileRequest
     */
    data?: string | null;
    /**
     * 用户的昵称，长度不能超过50个字符
     * @type {string}
     * @memberof UpdateProfileRequest
     */
    nickName?: string | null;
    /**
     * 兴趣标签
     * @type {string}
     * @memberof UpdateProfileRequest
     */
    interestTags?: string | null;
    /**
     * 个人简介，长度不能超过500个字符
     * @type {string}
     * @memberof UpdateProfileRequest
     */
    biography?: string | null;
    /**
     * 性别，长度不能超过15个字符
     * @type {string}
     * @memberof UpdateProfileRequest
     */
    gender?: string | null;
    /**
     * 生日
     * @type {Date}
     * @memberof UpdateProfileRequest
     */
    birthday?: Date | null;
    /**
     * 职业，长度不能超过50个字符
     * @type {string}
     * @memberof UpdateProfileRequest
     */
    occupation?: string | null;
    /**
     * 学历，长度不能超过50个字符
     * @type {string}
     * @memberof UpdateProfileRequest
     */
    education?: string | null;
    /**
     * 联系方式，长度不能超过255个字符
     * @type {string}
     * @memberof UpdateProfileRequest
     */
    contact?: string | null;
    /**
     * 语言，长度不能超过50个字符
     * @type {string}
     * @memberof UpdateProfileRequest
     */
    languages?: string | null;
    /**
     * 社交网络链接，长度不能超过255个字符
     * @type {string}
     * @memberof UpdateProfileRequest
     */
    socialLinks?: string | null;
    /**
     * 婚姻状态，长度不能超过20个字符
     * @type {string}
     * @memberof UpdateProfileRequest
     */
    relationshipStatus?: string | null;
    /**
     * 公司，长度不能超过100个字符
     * @type {string}
     * @memberof UpdateProfileRequest
     */
    company?: string | null;
    /**
     * 行业，长度不能超过50个字符
     * @type {string}
     * @memberof UpdateProfileRequest
     */
    industry?: string | null;
    /**
     * 行业职位，长度不能超过50个字符
     * @type {string}
     * @memberof UpdateProfileRequest
     */
    companyPosition?: string | null;
    /**
     * 私密设置，长度不能超过500个字符
     * @type {string}
     * @memberof UpdateProfileRequest
     */
    privateSettings?: string | null;
    /**
     * 是否启用二步验证
     * @type {boolean}
     * @memberof UpdateProfileRequest
     */
    enable2FAAuth?: boolean | null;
    /**
     * 是否启用账号登录
     * @type {boolean}
     * @memberof UpdateProfileRequest
     */
    enableUserNameSignIn?: boolean | null;
    /**
     * 是否启用邮箱登录
     * @type {boolean}
     * @memberof UpdateProfileRequest
     */
    enableEmailSignIn?: boolean | null;
    /**
     * 是否启用手机登录
     * @type {boolean}
     * @memberof UpdateProfileRequest
     */
    enablePhoneSignIn?: boolean | null;
    /**
     * 是否启用UnionID登录
     * @type {boolean}
     * @memberof UpdateProfileRequest
     */
    enableUnionIDSignIn?: boolean | null;
    /**
     * 是否启用OAuth2登录
     * @type {boolean}
     * @memberof UpdateProfileRequest
     */
    enableOAuth?: boolean | null;
}

/**
 * Check if a given object implements the UpdateProfileRequest interface.
 */
export function instanceOfUpdateProfileRequest(value: object): value is UpdateProfileRequest {
    return true;
}

export function UpdateProfileRequestFromJSON(json: any): UpdateProfileRequest {
    return UpdateProfileRequestFromJSONTyped(json, false);
}

export function UpdateProfileRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateProfileRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'avatar': json['avatar'] == null ? undefined : json['avatar'],
        'data': json['data'] == null ? undefined : json['data'],
        'nickName': json['nickName'] == null ? undefined : json['nickName'],
        'interestTags': json['interestTags'] == null ? undefined : json['interestTags'],
        'biography': json['biography'] == null ? undefined : json['biography'],
        'gender': json['gender'] == null ? undefined : json['gender'],
        'birthday': json['birthday'] == null ? undefined : (new Date(json['birthday'])),
        'occupation': json['occupation'] == null ? undefined : json['occupation'],
        'education': json['education'] == null ? undefined : json['education'],
        'contact': json['contact'] == null ? undefined : json['contact'],
        'languages': json['languages'] == null ? undefined : json['languages'],
        'socialLinks': json['socialLinks'] == null ? undefined : json['socialLinks'],
        'relationshipStatus': json['relationshipStatus'] == null ? undefined : json['relationshipStatus'],
        'company': json['company'] == null ? undefined : json['company'],
        'industry': json['industry'] == null ? undefined : json['industry'],
        'companyPosition': json['companyPosition'] == null ? undefined : json['companyPosition'],
        'privateSettings': json['privateSettings'] == null ? undefined : json['privateSettings'],
        'enable2FAAuth': json['enable2FAAuth'] == null ? undefined : json['enable2FAAuth'],
        'enableUserNameSignIn': json['enableUserNameSignIn'] == null ? undefined : json['enableUserNameSignIn'],
        'enableEmailSignIn': json['enableEmailSignIn'] == null ? undefined : json['enableEmailSignIn'],
        'enablePhoneSignIn': json['enablePhoneSignIn'] == null ? undefined : json['enablePhoneSignIn'],
        'enableUnionIDSignIn': json['enableUnionIDSignIn'] == null ? undefined : json['enableUnionIDSignIn'],
        'enableOAuth': json['enableOAuth'] == null ? undefined : json['enableOAuth'],
    };
}

export function UpdateProfileRequestToJSON(json: any): UpdateProfileRequest {
    return UpdateProfileRequestToJSONTyped(json, false);
}

export function UpdateProfileRequestToJSONTyped(value?: UpdateProfileRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'avatar': value['avatar'],
        'data': value['data'],
        'nickName': value['nickName'],
        'interestTags': value['interestTags'],
        'biography': value['biography'],
        'gender': value['gender'],
        'birthday': value['birthday'] == null ? undefined : ((value['birthday'] as any).toISOString()),
        'occupation': value['occupation'],
        'education': value['education'],
        'contact': value['contact'],
        'languages': value['languages'],
        'socialLinks': value['socialLinks'],
        'relationshipStatus': value['relationshipStatus'],
        'company': value['company'],
        'industry': value['industry'],
        'companyPosition': value['companyPosition'],
        'privateSettings': value['privateSettings'],
        'enable2FAAuth': value['enable2FAAuth'],
        'enableUserNameSignIn': value['enableUserNameSignIn'],
        'enableEmailSignIn': value['enableEmailSignIn'],
        'enablePhoneSignIn': value['enablePhoneSignIn'],
        'enableUnionIDSignIn': value['enableUnionIDSignIn'],
        'enableOAuth': value['enableOAuth'],
    };
}

