/* tslint:disable */
/* eslint-disable */
/**
 * 全部  API 文档
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface User
 */
export interface User {
    /**
     * 
     * @type {number}
     * @memberof User
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    platform?: string | null;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    unionID?: string | null;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    nickName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    avatar?: string | null;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    data?: string | null;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    userName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    pwd?: string | null;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    email?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof User
     */
    emailIsValid?: boolean;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    phone?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof User
     */
    phoneIsValid?: boolean;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    relationChain?: string | null;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    interestTags?: string | null;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    biography?: string | null;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    gender?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof User
     */
    birthday?: Date | null;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    occupation?: string | null;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    education?: string | null;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    contact?: string | null;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    languages?: string | null;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    socialLinks?: string | null;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    relationshipStatus?: string | null;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    company?: string | null;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    industry?: string | null;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    companyPosition?: string | null;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    privateSettings?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof User
     */
    isLock?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof User
     */
    lockUntil?: Date;
    /**
     * 
     * @type {boolean}
     * @memberof User
     */
    enableUserNameSignIn?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof User
     */
    enableEmailSignIn?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof User
     */
    enablePhoneSignIn?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof User
     */
    enableUnionIDSignIn?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof User
     */
    enableOAuth?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof User
     */
    enable2FAAuth?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof User
     */
    createDate?: Date;
    /**
     * 
     * @type {Date}
     * @memberof User
     */
    lastUpdate?: Date;
}

/**
 * Check if a given object implements the User interface.
 */
export function instanceOfUser(value: object): value is User {
    return true;
}

export function UserFromJSON(json: any): User {
    return UserFromJSONTyped(json, false);
}

export function UserFromJSONTyped(json: any, ignoreDiscriminator: boolean): User {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'platform': json['platform'] == null ? undefined : json['platform'],
        'unionID': json['unionID'] == null ? undefined : json['unionID'],
        'nickName': json['nickName'] == null ? undefined : json['nickName'],
        'avatar': json['avatar'] == null ? undefined : json['avatar'],
        'data': json['data'] == null ? undefined : json['data'],
        'userName': json['userName'] == null ? undefined : json['userName'],
        'pwd': json['pwd'] == null ? undefined : json['pwd'],
        'email': json['email'] == null ? undefined : json['email'],
        'emailIsValid': json['emailIsValid'] == null ? undefined : json['emailIsValid'],
        'phone': json['phone'] == null ? undefined : json['phone'],
        'phoneIsValid': json['phoneIsValid'] == null ? undefined : json['phoneIsValid'],
        'relationChain': json['relationChain'] == null ? undefined : json['relationChain'],
        'interestTags': json['interestTags'] == null ? undefined : json['interestTags'],
        'biography': json['biography'] == null ? undefined : json['biography'],
        'gender': json['gender'] == null ? undefined : json['gender'],
        'birthday': json['birthday'] == null ? undefined : (new Date(json['birthday'])),
        'occupation': json['occupation'] == null ? undefined : json['occupation'],
        'education': json['education'] == null ? undefined : json['education'],
        'contact': json['contact'] == null ? undefined : json['contact'],
        'languages': json['languages'] == null ? undefined : json['languages'],
        'socialLinks': json['socialLinks'] == null ? undefined : json['socialLinks'],
        'relationshipStatus': json['relationshipStatus'] == null ? undefined : json['relationshipStatus'],
        'company': json['company'] == null ? undefined : json['company'],
        'industry': json['industry'] == null ? undefined : json['industry'],
        'companyPosition': json['companyPosition'] == null ? undefined : json['companyPosition'],
        'privateSettings': json['privateSettings'] == null ? undefined : json['privateSettings'],
        'isLock': json['isLock'] == null ? undefined : json['isLock'],
        'lockUntil': json['lockUntil'] == null ? undefined : (new Date(json['lockUntil'])),
        'enableUserNameSignIn': json['enableUserNameSignIn'] == null ? undefined : json['enableUserNameSignIn'],
        'enableEmailSignIn': json['enableEmailSignIn'] == null ? undefined : json['enableEmailSignIn'],
        'enablePhoneSignIn': json['enablePhoneSignIn'] == null ? undefined : json['enablePhoneSignIn'],
        'enableUnionIDSignIn': json['enableUnionIDSignIn'] == null ? undefined : json['enableUnionIDSignIn'],
        'enableOAuth': json['enableOAuth'] == null ? undefined : json['enableOAuth'],
        'enable2FAAuth': json['enable2FAAuth'] == null ? undefined : json['enable2FAAuth'],
        'createDate': json['createDate'] == null ? undefined : (new Date(json['createDate'])),
        'lastUpdate': json['lastUpdate'] == null ? undefined : (new Date(json['lastUpdate'])),
    };
}

export function UserToJSON(json: any): User {
    return UserToJSONTyped(json, false);
}

export function UserToJSONTyped(value?: User | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'platform': value['platform'],
        'unionID': value['unionID'],
        'nickName': value['nickName'],
        'avatar': value['avatar'],
        'data': value['data'],
        'userName': value['userName'],
        'pwd': value['pwd'],
        'email': value['email'],
        'emailIsValid': value['emailIsValid'],
        'phone': value['phone'],
        'phoneIsValid': value['phoneIsValid'],
        'relationChain': value['relationChain'],
        'interestTags': value['interestTags'],
        'biography': value['biography'],
        'gender': value['gender'],
        'birthday': value['birthday'] == null ? undefined : ((value['birthday'] as any).toISOString()),
        'occupation': value['occupation'],
        'education': value['education'],
        'contact': value['contact'],
        'languages': value['languages'],
        'socialLinks': value['socialLinks'],
        'relationshipStatus': value['relationshipStatus'],
        'company': value['company'],
        'industry': value['industry'],
        'companyPosition': value['companyPosition'],
        'privateSettings': value['privateSettings'],
        'isLock': value['isLock'],
        'lockUntil': value['lockUntil'] == null ? undefined : ((value['lockUntil']).toISOString()),
        'enableUserNameSignIn': value['enableUserNameSignIn'],
        'enableEmailSignIn': value['enableEmailSignIn'],
        'enablePhoneSignIn': value['enablePhoneSignIn'],
        'enableUnionIDSignIn': value['enableUnionIDSignIn'],
        'enableOAuth': value['enableOAuth'],
        'enable2FAAuth': value['enable2FAAuth'],
        'createDate': value['createDate'] == null ? undefined : ((value['createDate']).toISOString()),
        'lastUpdate': value['lastUpdate'] == null ? undefined : ((value['lastUpdate']).toISOString()),
    };
}

