/* tslint:disable */
/* eslint-disable */
/**
 * 用户全部 API 文档
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserFollowersResult } from './UserFollowersResult';
import {
    UserFollowersResultFromJSON,
    UserFollowersResultFromJSONTyped,
    UserFollowersResultToJSON,
    UserFollowersResultToJSONTyped,
} from './UserFollowersResult';

/**
 * 
 * @export
 * @interface UserFollowersResultApiResponse
 */
export interface UserFollowersResultApiResponse {
    /**
     * 状态码
     * @type {number}
     * @memberof UserFollowersResultApiResponse
     */
    code?: number;
    /**
     * 
     * @type {UserFollowersResult}
     * @memberof UserFollowersResultApiResponse
     */
    data?: UserFollowersResult;
    /**
     * 错误信息
     * @type {string}
     * @memberof UserFollowersResultApiResponse
     */
    error?: string | null;
}

/**
 * Check if a given object implements the UserFollowersResultApiResponse interface.
 */
export function instanceOfUserFollowersResultApiResponse(value: object): value is UserFollowersResultApiResponse {
    return true;
}

export function UserFollowersResultApiResponseFromJSON(json: any): UserFollowersResultApiResponse {
    return UserFollowersResultApiResponseFromJSONTyped(json, false);
}

export function UserFollowersResultApiResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserFollowersResultApiResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'data': json['data'] == null ? undefined : UserFollowersResultFromJSON(json['data']),
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function UserFollowersResultApiResponseToJSON(json: any): UserFollowersResultApiResponse {
    return UserFollowersResultApiResponseToJSONTyped(json, false);
}

export function UserFollowersResultApiResponseToJSONTyped(value?: UserFollowersResultApiResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'data': UserFollowersResultToJSON(value['data']),
        'error': value['error'],
    };
}

