/* tslint:disable */
/* eslint-disable */
/**
 * 用户全部 API 文档
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserLocationPostResult } from './UserLocationPostResult';
import {
    UserLocationPostResultFromJSON,
    UserLocationPostResultFromJSONTyped,
    UserLocationPostResultToJSON,
    UserLocationPostResultToJSONTyped,
} from './UserLocationPostResult';

/**
 * 
 * @export
 * @interface UserLocationPostResultApiResponse
 */
export interface UserLocationPostResultApiResponse {
    /**
     * 状态码
     * @type {number}
     * @memberof UserLocationPostResultApiResponse
     */
    code?: number;
    /**
     * 
     * @type {UserLocationPostResult}
     * @memberof UserLocationPostResultApiResponse
     */
    data?: UserLocationPostResult;
    /**
     * 错误信息
     * @type {string}
     * @memberof UserLocationPostResultApiResponse
     */
    error?: string | null;
}

/**
 * Check if a given object implements the UserLocationPostResultApiResponse interface.
 */
export function instanceOfUserLocationPostResultApiResponse(value: object): value is UserLocationPostResultApiResponse {
    return true;
}

export function UserLocationPostResultApiResponseFromJSON(json: any): UserLocationPostResultApiResponse {
    return UserLocationPostResultApiResponseFromJSONTyped(json, false);
}

export function UserLocationPostResultApiResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserLocationPostResultApiResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'data': json['data'] == null ? undefined : UserLocationPostResultFromJSON(json['data']),
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function UserLocationPostResultApiResponseToJSON(json: any): UserLocationPostResultApiResponse {
    return UserLocationPostResultApiResponseToJSONTyped(json, false);
}

export function UserLocationPostResultApiResponseToJSONTyped(value?: UserLocationPostResultApiResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'data': UserLocationPostResultToJSON(value['data']),
        'error': value['error'],
    };
}

