/* tslint:disable */
/* eslint-disable */
/**
 * 用户全部 API 文档
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserCurrency } from './UserCurrency';
import {
    UserCurrencyFromJSON,
    UserCurrencyFromJSONTyped,
    UserCurrencyToJSON,
    UserCurrencyToJSONTyped,
} from './UserCurrency';

/**
 * 
 * @export
 * @interface UserCurrencyListApiResponse
 */
export interface UserCurrencyListApiResponse {
    /**
     * 状态码
     * @type {number}
     * @memberof UserCurrencyListApiResponse
     */
    code?: number;
    /**
     * 响应数据
     * @type {Array<UserCurrency>}
     * @memberof UserCurrencyListApiResponse
     */
    data?: Array<UserCurrency> | null;
    /**
     * 错误信息
     * @type {string}
     * @memberof UserCurrencyListApiResponse
     */
    error?: string | null;
}

/**
 * Check if a given object implements the UserCurrencyListApiResponse interface.
 */
export function instanceOfUserCurrencyListApiResponse(value: object): value is UserCurrencyListApiResponse {
    return true;
}

export function UserCurrencyListApiResponseFromJSON(json: any): UserCurrencyListApiResponse {
    return UserCurrencyListApiResponseFromJSONTyped(json, false);
}

export function UserCurrencyListApiResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserCurrencyListApiResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(UserCurrencyFromJSON)),
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function UserCurrencyListApiResponseToJSON(json: any): UserCurrencyListApiResponse {
    return UserCurrencyListApiResponseToJSONTyped(json, false);
}

export function UserCurrencyListApiResponseToJSONTyped(value?: UserCurrencyListApiResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(UserCurrencyToJSON)),
        'error': value['error'],
    };
}

