/* tslint:disable */
/* eslint-disable */
/**
 * 用户全部 API 文档
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 用户令牌实体，用于管理用户的访问令牌及其相关信息。
 * @export
 * @interface UserAccessToken
 */
export interface UserAccessToken {
    /**
     * 用户令牌的唯一标识符。
     * @type {number}
     * @memberof UserAccessToken
     */
    id?: number;
    /**
     * 与令牌关联的用户ID。
     * @type {number}
     * @memberof UserAccessToken
     */
    userID?: number;
    /**
     * 指示令牌是否处于启用状态。
     * @type {boolean}
     * @memberof UserAccessToken
     */
    enable?: boolean;
    /**
     * 令牌拥有的权限列表，多个权限以逗号分隔。
     * @type {string}
     * @memberof UserAccessToken
     */
    permissions?: string | null;
    /**
     * 令牌的标题或名称，用于标识令牌。
     * @type {string}
     * @memberof UserAccessToken
     */
    title?: string | null;
    /**
     * 访问令牌的具体值，用于身份验证。
     * @type {string}
     * @memberof UserAccessToken
     */
    accessToken?: string | null;
    /**
     * 用于分类或标记令牌的标签。
     * @type {string}
     * @memberof UserAccessToken
     */
    tags?: string | null;
    /**
     * 令牌的详细描述信息。
     * @type {string}
     * @memberof UserAccessToken
     */
    description?: string | null;
    /**
     * 令牌的过期时间，超过该时间令牌将失效。
     * @type {Date}
     * @memberof UserAccessToken
     */
    expireTime?: Date;
    /**
     * 令牌的创建日期，默认为当前时间。
     * @type {Date}
     * @memberof UserAccessToken
     */
    createDate?: Date;
    /**
     * 令牌的最后更新日期，默认为当前时间。
     * @type {Date}
     * @memberof UserAccessToken
     */
    lastUpdate?: Date;
}

/**
 * Check if a given object implements the UserAccessToken interface.
 */
export function instanceOfUserAccessToken(value: object): value is UserAccessToken {
    return true;
}

export function UserAccessTokenFromJSON(json: any): UserAccessToken {
    return UserAccessTokenFromJSONTyped(json, false);
}

export function UserAccessTokenFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserAccessToken {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'userID': json['userID'] == null ? undefined : json['userID'],
        'enable': json['enable'] == null ? undefined : json['enable'],
        'permissions': json['permissions'] == null ? undefined : json['permissions'],
        'title': json['title'] == null ? undefined : json['title'],
        'accessToken': json['accessToken'] == null ? undefined : json['accessToken'],
        'tags': json['tags'] == null ? undefined : json['tags'],
        'description': json['description'] == null ? undefined : json['description'],
        'expireTime': json['expireTime'] == null ? undefined : (new Date(json['expireTime'])),
        'createDate': json['createDate'] == null ? undefined : (new Date(json['createDate'])),
        'lastUpdate': json['lastUpdate'] == null ? undefined : (new Date(json['lastUpdate'])),
    };
}

export function UserAccessTokenToJSON(json: any): UserAccessToken {
    return UserAccessTokenToJSONTyped(json, false);
}

export function UserAccessTokenToJSONTyped(value?: UserAccessToken | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'userID': value['userID'],
        'enable': value['enable'],
        'permissions': value['permissions'],
        'title': value['title'],
        'accessToken': value['accessToken'],
        'tags': value['tags'],
        'description': value['description'],
        'expireTime': value['expireTime'] == null ? undefined : ((value['expireTime']).toISOString()),
        'createDate': value['createDate'] == null ? undefined : ((value['createDate']).toISOString()),
        'lastUpdate': value['lastUpdate'] == null ? undefined : ((value['lastUpdate']).toISOString()),
    };
}

