/* tslint:disable */
/* eslint-disable */
/**
 * 用户全部 API 文档
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CurrencyTransaction } from './CurrencyTransaction';
import {
    CurrencyTransactionFromJSON,
    CurrencyTransactionFromJSONTyped,
    CurrencyTransactionToJSON,
    CurrencyTransactionToJSONTyped,
} from './CurrencyTransaction';

/**
 * 
 * @export
 * @interface UserCurrencyCurrencyTransResult
 */
export interface UserCurrencyCurrencyTransResult {
    /**
     * 
     * @type {number}
     * @memberof UserCurrencyCurrencyTransResult
     */
    total?: number;
    /**
     * 
     * @type {Array<CurrencyTransaction>}
     * @memberof UserCurrencyCurrencyTransResult
     */
    data?: Array<CurrencyTransaction> | null;
}

/**
 * Check if a given object implements the UserCurrencyCurrencyTransResult interface.
 */
export function instanceOfUserCurrencyCurrencyTransResult(value: object): value is UserCurrencyCurrencyTransResult {
    return true;
}

export function UserCurrencyCurrencyTransResultFromJSON(json: any): UserCurrencyCurrencyTransResult {
    return UserCurrencyCurrencyTransResultFromJSONTyped(json, false);
}

export function UserCurrencyCurrencyTransResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserCurrencyCurrencyTransResult {
    if (json == null) {
        return json;
    }
    return {
        
        'total': json['total'] == null ? undefined : json['total'],
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(CurrencyTransactionFromJSON)),
    };
}

export function UserCurrencyCurrencyTransResultToJSON(json: any): UserCurrencyCurrencyTransResult {
    return UserCurrencyCurrencyTransResultToJSONTyped(json, false);
}

export function UserCurrencyCurrencyTransResultToJSONTyped(value?: UserCurrencyCurrencyTransResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total': value['total'],
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(CurrencyTransactionToJSON)),
    };
}

