/* tslint:disable */
/* eslint-disable */
/**
 * 全部  API 文档
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserSettingPostResult
 */
export interface UserSettingPostResult {
    /**
     * 
     * @type {number}
     * @memberof UserSettingPostResult
     */
    id?: number;
}

/**
 * Check if a given object implements the UserSettingPostResult interface.
 */
export function instanceOfUserSettingPostResult(value: object): value is UserSettingPostResult {
    return true;
}

export function UserSettingPostResultFromJSON(json: any): UserSettingPostResult {
    return UserSettingPostResultFromJSONTyped(json, false);
}

export function UserSettingPostResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserSettingPostResult {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function UserSettingPostResultToJSON(json: any): UserSettingPostResult {
    return UserSettingPostResultToJSONTyped(json, false);
}

export function UserSettingPostResultToJSONTyped(value?: UserSettingPostResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
    };
}

