/* tslint:disable */
/* eslint-disable */
/**
 * 全部  API 文档
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 用户配置实体，用于存储用户的个性化设置。
 * @export
 * @interface UserSetting
 */
export interface UserSetting {
    /**
     * 用户的唯一标识符。
     * @type {number}
     * @memberof UserSetting
     */
    id?: number;
    /**
     * 关联的用户ID，表示该配置属于哪个用户。
     * @type {number}
     * @memberof UserSetting
     */
    userID: number;
    /**
     * 提供商的唯一代码，用于标识服务提供者。
     * @type {string}
     * @memberof UserSetting
     */
    providerCode?: string | null;
    /**
     * 组的唯一代码，用于分类设置项。
     * @type {string}
     * @memberof UserSetting
     */
    groupCode?: string | null;
    /**
     * 设置项的唯一代码或键名，用于标识具体的配置项。
     * @type {string}
     * @memberof UserSetting
     */
    code: string;
    /**
     * 设置项的具体值或选项。
     * @type {string}
     * @memberof UserSetting
     */
    value: string;
    /**
     * 用于对设置项进行分类或标记的标签。
     * @type {string}
     * @memberof UserSetting
     */
    tags?: string | null;
    /**
     * 设置项的详细描述，说明其作用或用途。
     * @type {string}
     * @memberof UserSetting
     */
    description?: string | null;
    /**
     * 指示该设置项是否在前端界面中可用。
     * @type {boolean}
     * @memberof UserSetting
     */
    frontendUsable?: boolean;
    /**
     * 设置项的创建时间。
     * @type {Date}
     * @memberof UserSetting
     */
    createDate?: Date;
    /**
     * 设置项的最后更新时间。
     * @type {Date}
     * @memberof UserSetting
     */
    lastUpdate?: Date;
}

/**
 * Check if a given object implements the UserSetting interface.
 */
export function instanceOfUserSetting(value: object): value is UserSetting {
    if (!('userID' in value) || value['userID'] === undefined) return false;
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function UserSettingFromJSON(json: any): UserSetting {
    return UserSettingFromJSONTyped(json, false);
}

export function UserSettingFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserSetting {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'userID': json['userID'],
        'providerCode': json['providerCode'] == null ? undefined : json['providerCode'],
        'groupCode': json['groupCode'] == null ? undefined : json['groupCode'],
        'code': json['code'],
        'value': json['value'],
        'tags': json['tags'] == null ? undefined : json['tags'],
        'description': json['description'] == null ? undefined : json['description'],
        'frontendUsable': json['frontendUsable'] == null ? undefined : json['frontendUsable'],
        'createDate': json['createDate'] == null ? undefined : (new Date(json['createDate'])),
        'lastUpdate': json['lastUpdate'] == null ? undefined : (new Date(json['lastUpdate'])),
    };
}

export function UserSettingToJSON(json: any): UserSetting {
    return UserSettingToJSONTyped(json, false);
}

export function UserSettingToJSONTyped(value?: UserSetting | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'userID': value['userID'],
        'providerCode': value['providerCode'],
        'groupCode': value['groupCode'],
        'code': value['code'],
        'value': value['value'],
        'tags': value['tags'],
        'description': value['description'],
        'frontendUsable': value['frontendUsable'],
        'createDate': value['createDate'] == null ? undefined : ((value['createDate']).toISOString()),
        'lastUpdate': value['lastUpdate'] == null ? undefined : ((value['lastUpdate']).toISOString()),
    };
}

