/* tslint:disable */
/* eslint-disable */
/**
 * 用户全部 API 文档
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CommonFriendModel } from './CommonFriendModel';
import {
    CommonFriendModelFromJSON,
    CommonFriendModelFromJSONTyped,
    CommonFriendModelToJSON,
    CommonFriendModelToJSONTyped,
} from './CommonFriendModel';

/**
 * 
 * @export
 * @interface UserCommonInterestsResult
 */
export interface UserCommonInterestsResult {
    /**
     * 
     * @type {number}
     * @memberof UserCommonInterestsResult
     */
    totalFollowers?: number;
    /**
     * 
     * @type {Array<CommonFriendModel>}
     * @memberof UserCommonInterestsResult
     */
    data?: Array<CommonFriendModel> | null;
}

/**
 * Check if a given object implements the UserCommonInterestsResult interface.
 */
export function instanceOfUserCommonInterestsResult(value: object): value is UserCommonInterestsResult {
    return true;
}

export function UserCommonInterestsResultFromJSON(json: any): UserCommonInterestsResult {
    return UserCommonInterestsResultFromJSONTyped(json, false);
}

export function UserCommonInterestsResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserCommonInterestsResult {
    if (json == null) {
        return json;
    }
    return {
        
        'totalFollowers': json['totalFollowers'] == null ? undefined : json['totalFollowers'],
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(CommonFriendModelFromJSON)),
    };
}

export function UserCommonInterestsResultToJSON(json: any): UserCommonInterestsResult {
    return UserCommonInterestsResultToJSONTyped(json, false);
}

export function UserCommonInterestsResultToJSONTyped(value?: UserCommonInterestsResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'totalFollowers': value['totalFollowers'],
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(CommonFriendModelToJSON)),
    };
}

