/* tslint:disable */
/* eslint-disable */
/**
 * 用户全部 API 文档
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserMutualFollowingsResult } from './UserMutualFollowingsResult';
import {
    UserMutualFollowingsResultFromJSON,
    UserMutualFollowingsResultFromJSONTyped,
    UserMutualFollowingsResultToJSON,
    UserMutualFollowingsResultToJSONTyped,
} from './UserMutualFollowingsResult';

/**
 * 
 * @export
 * @interface UserMutualFollowingsResultApiResponse
 */
export interface UserMutualFollowingsResultApiResponse {
    /**
     * 状态码
     * @type {number}
     * @memberof UserMutualFollowingsResultApiResponse
     */
    code?: number;
    /**
     * 
     * @type {UserMutualFollowingsResult}
     * @memberof UserMutualFollowingsResultApiResponse
     */
    data?: UserMutualFollowingsResult;
    /**
     * 错误信息
     * @type {string}
     * @memberof UserMutualFollowingsResultApiResponse
     */
    error?: string | null;
}

/**
 * Check if a given object implements the UserMutualFollowingsResultApiResponse interface.
 */
export function instanceOfUserMutualFollowingsResultApiResponse(value: object): value is UserMutualFollowingsResultApiResponse {
    return true;
}

export function UserMutualFollowingsResultApiResponseFromJSON(json: any): UserMutualFollowingsResultApiResponse {
    return UserMutualFollowingsResultApiResponseFromJSONTyped(json, false);
}

export function UserMutualFollowingsResultApiResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserMutualFollowingsResultApiResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'] == null ? undefined : json['code'],
        'data': json['data'] == null ? undefined : UserMutualFollowingsResultFromJSON(json['data']),
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function UserMutualFollowingsResultApiResponseToJSON(json: any): UserMutualFollowingsResultApiResponse {
    return UserMutualFollowingsResultApiResponseToJSONTyped(json, false);
}

export function UserMutualFollowingsResultApiResponseToJSONTyped(value?: UserMutualFollowingsResultApiResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'data': UserMutualFollowingsResultToJSON(value['data']),
        'error': value['error'],
    };
}

